window.PEMWE_AI_ENTRIES = {
  ...(window.PEMWE_AI_ENTRIES || {}),
  B: {
    articles: [
      {
        title: 'Heteroatom dopants overcome the activity-stability trade-off in RuO2 for acidic oxygen evolution',
        journalInfo: 'Nature Communications, 2025, DOI: 10.1038/s41467-025-62036-x',
        publicationYear: '2025',
        publicationId: 'Article 62036-x',
        sampleName: 'Ta/B-RuO2; Ta- and B-codoped nanoporous RuO2 with Ru-O-Ta frameworks and Ru-O-B active sites',
        synthesis: 'Ru-Ta-B precursor ribbons were prepared by melt spinning, then selectively etched by electrochemical corrosion to remove the B-rich phase and transform RuB2 into RuO2. The etched ribbons were annealed in a muffle furnace to obtain a core-shell catalyst containing Ta/B-doped RuO2 shell and Ru-Ta alloy core.',
        activity: 'Acidic OER overpotential of 170 mV at 10 mA cm-2 with a Tafel slope of 44 mV dec-1. In PEMWE, the Ta/B-RuO2 anode reached 1.0 A cm-2 at about 1.6 V and showed polarization up to about 2 A cm-2.',
        stability: 'PEMWE stability: 120 h at 0.2 A cm-2. The reported cell operated around 1.45 V during the 120 h test at 200 mA cm-2, with suppressed Ru dissolution relative to B-RuO2 and RuO2.',
        notes: 'Mechanistic point: Ru-O-Ta frameworks stabilize Ru by mediating bridging oxygen and preferentially replenishing oxygen vacancies, steering OER toward AEM-like behavior. Ru-O-Ta/B sites lower the rate-determining-step barrier. This same article is also listed under Ta because it is a Ta/B codoped RuO2 system.',
        pdfFileName: '7-Ta-RuO2-0.2A-120h-450C.pdf',
        pdfFileSize: '4.2 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  F: {
    articles: [
      {
        title: 'Accelerated Deprotonation Triggered by Fluorinated RuO2 Enables Efficient and Stable Acidic Water Electrolysis',
        journalInfo: 'Journal of the American Chemical Society, 2026, 148, 217-227, DOI: 10.1021/jacs.5c08859',
        publicationYear: '2026',
        publicationId: '148, 217-227',
        sampleName: 'RuO1.86F0.14; fluorinated RuO2',
        synthesis: 'Fluorinated RuO2 was synthesized using nitrate-assisted formation of porous nanomeshes and ammonium fluoride as both fluorinating/etching agent. Nitrate decomposition generated NO2 to promote pores, while HF released from ammonium fluoride introduced F into the RuO2 lattice/surface.',
        activity: 'Acidic OER overpotential of 153 mV at 10 mA cm-2. In PEMWE, RuO1.86F0.14 required only about 1.63 V at 1 A cm-2.',
        stability: 'PEMWE stability: over 100 h at 1 A cm-2. Acidic OER stability exceeded 980 h at 10 mA cm-2 with a degradation rate of about 27 uV h-1.',
        notes: 'Mechanistic point: F- triggers a hydrogen-bond-mediated deprotonation pathway, accelerating proton transfer to bridging oxygen. The high electronegativity of F weakens Ru-O covalency, suppresses Ru overoxidation, and shifts the reaction away from lattice oxygen participation toward AEM-like behavior.',
        pdfFileName: '9-F0.14-RuO1.86-1A-100h-350C-.pdf',
        pdfFileSize: '9.8 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Si: {
    articles: [
      {
        title: 'Bulk and Surface Dual-Modification for Stabilizing RuO2 Anode in 2 A cm-2 PEMWE Operation',
        journalInfo: 'Advanced Materials, 2026, 38, e21819, DOI: 10.1002/adma.202521819',
        publicationYear: '2026',
        publicationId: '38, e21819',
        sampleName: 'Si@CrRuO2; Cr-substituted RuO2 with surface Si modification',
        synthesis: 'Si@CrRuO2 was synthesized by a two-step strategy. Cr was introduced into RuO2 to form CrRuO2 nanoparticles, followed by surface Si modification to create Si-O-Ru interfacial bonding and stabilize the catalyst/electrode interface.',
        activity: 'Cr doping lowered the acidic OER onset/overpotential relative to synthetic RuO2; surface Si modification further improved high-current behavior. PEMWE operation reached 2 A cm-2 at about 1.65 V.',
        stability: 'PEMWE stability: 350 h at 2 A cm-2. The work emphasizes stable industrial-relevant PEMWE operation by combining bulk Ru-valence stabilization with surface/interface protection.',
        notes: 'Mechanistic point: Cr modulates the bulk Ru valence and suppresses overoxidation, while Si stabilizes the reaction interface, inhibits catalyst reconstruction, and helps protect Cr dopants. This same article is also listed under Cr because the functional design is Cr bulk substitution plus Si surface modification.',
        pdfFileName: '5-SiCr-RuO2-2A-350h.pdf',
        pdfFileSize: '6.1 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Cr: {
    articles: [
      {
        title: 'Bulk and Surface Dual-Modification for Stabilizing RuO2 Anode in 2 A cm-2 PEMWE Operation',
        journalInfo: 'Advanced Materials, 2026, 38, e21819, DOI: 10.1002/adma.202521819',
        publicationYear: '2026',
        publicationId: '38, e21819',
        sampleName: 'Si@CrRuO2; Cr-substituted RuO2 with surface Si modification',
        synthesis: 'Si@CrRuO2 was synthesized by a two-step strategy. Cr was introduced into RuO2 to form CrRuO2 nanoparticles, followed by surface Si modification to create Si-O-Ru interfacial bonding and stabilize the catalyst/electrode interface.',
        activity: 'Cr doping lowered the acidic OER onset/overpotential relative to synthetic RuO2; surface Si modification further improved high-current behavior. PEMWE operation reached 2 A cm-2 at about 1.65 V.',
        stability: 'PEMWE stability: 350 h at 2 A cm-2. The work emphasizes stable industrial-relevant PEMWE operation by combining bulk Ru-valence stabilization with surface/interface protection.',
        notes: 'Mechanistic point: Cr modulates the bulk Ru valence and suppresses overoxidation, while Si stabilizes the reaction interface, inhibits catalyst reconstruction, and helps protect Cr dopants. This same article is also listed under Si because the functional design is Cr bulk substitution plus Si surface modification.',
        pdfFileName: '5-SiCr-RuO2-2A-350h.pdf',
        pdfFileSize: '6.1 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Mn: {
    articles: [
      {
        title: 'Hydroxylation Strategy Enables Ru-Mn Oxide for Stable Proton Exchange Membrane Water Electrolysis under 1 A cm-2',
        journalInfo: 'ACS Nano, 2025, 19, 8773-8785, DOI: 10.1021/acsnano.4c15900',
        publicationYear: '2025',
        publicationId: '19, 8773-8785',
        sampleName: 'H-Mn0.1Ru0.9O2; hydroxylated Mn-doped RuO2',
        synthesis: 'Mn-doped RuO2 was prepared using a hydrothermal route, followed by hydrogen peroxide-assisted hydroxylation. The dried black precipitate was annealed in air at 400 C for 3 h to obtain H-Mn0.1Ru0.9O2.',
        activity: 'Acidic OER overpotential of 169 mV at 10 mA cm-2. PEMWE device with H-Mn0.1Ru0.9O2 anode delivered 1 A cm-2 at about 1.65 V.',
        stability: 'PEMWE stability: about 80 h at 1 A cm-2 according to the file label and article title context; the article reports low voltage degradation over continuous tens of hours. Acidic OER stability exceeded 1000 h in electrolyte.',
        notes: 'Mechanistic point: hydroxylation keeps Ru below +4 and, together with Mn doping, promotes AEM rather than LOM. DEMS and DFT support lower energy barrier for *O to *OOH, stronger resistance to subsurface oxygen loss, and suppressed high-valence soluble Ru formation.',
        pdfFileName: '14-H-Mn0.1Ru0.9O2-1A-80h-400C.pdf',
        pdfFileSize: '7.9 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Sn: {
    articles: [
      {
        title: 'Customized reaction route for ruthenium oxide towards stabilized water oxidation in high-performance PEM electrolyzers',
        journalInfo: 'Nature Communications, 2023, DOI: 10.1038/s41467-023-36380-9',
        publicationYear: '2023',
        publicationId: 'Article 36380-9',
        sampleName: 'SnRuOx solid solution; M/Ru close to 1 in rutile-type MRuOx model catalysts',
        synthesis: 'SnRuOx was prepared as a rutile-type MRuOx oxide solid solution using a precursor route based on RuCl3/HMTA chemistry followed by air annealing. The methods section describes annealing dried Ru-HMTA precursor at 350 C for 5 h and acid washing; related MRuOx models were synthesized with controlled metal/Ru ratios.',
        activity: 'The MRuOx model series links Ru charge and OER route. SnRuOx showed favorable acidic OER performance and a customized reaction route relative to RuOx/CeRuOx/CrRuOx, with PEMWE single-cell performance suitable for long-term operation at 1 A cm-2.',
        stability: 'PEMWE stability: 1300 h at 1 A cm-2 with a degradation rate of 53 uV h-1 in a scalable single cell. The two local PDF filenames also indicate 1000-1200 h class durability at 1 A cm-2.',
        notes: 'Mechanistic point: Sn tunes Ru charge and the Ru-O-M motif, customizing the OER route and intermediate binding strength. The central claim is that reaction route, not bias alone, controls operational stability. Two local PDFs appear to be duplicate copies of this same article and are merged into one Sn entry.',
        pdfFileName: '2-SnRuOx-1A-1200h-400C.pdf; 4-SnRuOx-1A-1000h-350C.pdf',
        pdfFileSize: '1.7 MB each',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Zr: {
    articles: [
      {
        title: 'Lewis Acid-Mediated Interfacial Water Supply for Sustainable Proton Exchange Membrane Water Electrolysis',
        journalInfo: 'Journal of the American Chemical Society, 2024, 146, 35438-35448, DOI: 10.1021/jacs.4c14529',
        publicationYear: '2024',
        publicationId: '146, 35438-35448',
        sampleName: 'ZrO2-RuO2; Lewis-acid-modified RuO2 heterostructure',
        synthesis: 'Lewis-acid-modified RuO2 catalysts (ZrO2-RuO2, TiO2-RuO2, HfO2-RuO2) were synthesized by a hydrothermal-annealing strategy. ZrO2-RuO2 is the optimized interfacial-water-supply sample highlighted in the PDF.',
        activity: 'ZrO2-RuO2 displayed an overpotential of 170 mV at 10 mA cm-2 for acidic OER. In PEMWE it maintained robust operation at 2 A cm-2.',
        stability: 'PEMWE stability: 100 h at 2 A cm-2. Acidic OER durability reached 1800 h at 10 mA cm-2 with only about 25 mV degradation, corresponding to about 0.014 mV h-1.',
        notes: 'Mechanistic point: hard Lewis acid ZrO2 modifies interfacial hydrogen bonding and shifts the local water network from rigid hydrogen bonding toward free water, improving water supply and proton transfer. This changes the dissolution/deprotonation environment rather than simply tuning Ru electronic structure.',
        pdfFileName: '11-ZrO2-RuO2-2A-100h-400C.pdf',
        pdfFileSize: '9.8 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Mo: {
    articles: [
      {
        title: 'Heterophase RuO2 oxygen evolution catalyst for durable proton exchange membrane water electrolysis',
        journalInfo: 'Science Advances, 2025',
        publicationYear: '2025',
        publicationId: 'PDF file 1-Mo-RuOx; article details extracted from local PDF',
        sampleName: 'AC-MoRuOx; amorphous-crystalline heterophase Mo-doped RuOx/RuO2 catalyst',
        synthesis: 'Ru acetylacetonate, Mo acetylacetonate, and poly(vinyl pyrrolidone) were dissolved in ethanol, evaporated to a gelatinous precursor, and annealed in air. PVP served as steric stabilizer, pore-forming template, and crystallization regulator to form amorphous-crystalline MoRuOx heterophase architecture.',
        activity: 'Acidic OER overpotential of 180 mV at 10 mA cm-2 with Tafel slope around 48.3 mV dec-1. PEMWE device reached about 2.0 A cm-2 at 1.65 V.',
        stability: 'PEMWE stability: 2000 h at 1.0 A cm-2 and 1000 h at 1.5 A cm-2. Acidic OER stability exceeded 3000 h at 10 mA cm-2 with negligible Ru dissolution.',
        notes: 'Mechanistic point: Mo dopants are enriched near heterophase interfaces, lowering Ru charge and weakening Ru-O covalency. Crystalline domains support electron transport, amorphous domains buffer structural stress, and the heterophase interface addresses the activity-stability trade-off.',
        pdfFileName: '1-Mo-RuOx@1.5A-1000h-400 C.pdf',
        pdfFileSize: '2.5 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  W: {
    articles: [
      {
        title: 'Introducing Bronsted acid sites to accelerate the bridging-oxygen-assisted deprotonation in acidic water oxidation',
        journalInfo: 'Nature Communications, 2022, DOI: 10.1038/s41467-022-32581-w',
        publicationYear: '2022',
        publicationId: 'Article 32581-w',
        sampleName: 'Ru-W binary oxide; rutile RuWOx/RuW5O1x-type catalyst with W-O-Ru Bronsted acid sites',
        synthesis: 'Ru-W binary oxide catalysts were synthesized by a modified sol-gel method. Feed ratios of metal precursors were adjusted to obtain rutile Ru-W oxide nanoparticles with homogeneous Ru, W, and O distribution, followed by drying and annealing at 500 C for 1 h.',
        activity: 'Acidic OER overpotential of 235 mV at 10 mA cm-2. The paper focuses on accelerating proton transfer/deprotonation rather than maximizing PEMWE device current.',
        stability: 'Acidic OER stability: 550 h with low degradation rate of 0.014 mV h-1. The local file name indicates PEMWE-relevant testing around 150 h at 2 A cm-2, but the extracted main-text evidence most clearly supports the 550 h acidic OER durability.',
        notes: 'Mechanistic point: W-O-Ru Bronsted acid sites accelerate bridging-oxygen-assisted deprotonation by facilitating proton transfer from oxo intermediates to neighboring bridging oxygen. The article also states the strategy is extendable to other Ru-M oxides such as Cr, Mo, Nb, Ta, and Ti.',
        pdfFileName: '3-Ru-W oxide-2A-150h-400C.pdf',
        pdfFileSize: '4.0 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Sb: {
    articles: [
      {
        title: 'Accelerated Proton Transfer in Asymmetric Active Units for Sustainable Acidic Oxygen Evolution Reaction',
        journalInfo: 'Journal of the American Chemical Society, 2024, 146, 23146-23157, DOI: 10.1021/jacs.4c05070',
        publicationYear: '2024',
        publicationId: '146, 23146-23157',
        sampleName: 'Ru0.8Sb0.2O2; Sb-containing Ru-M-O binary solid-solution oxide',
        synthesis: 'Ru0.8Sb0.2O2 was synthesized by continuous hydrothermal and calcination strategies to form a rutile solid solution. EDS/ICP-MS showed uniform Ru and Sb mixing; In and Sn analogues were prepared as references.',
        activity: 'Acidic OER overpotential of 160 mV at 10 mA cm-2. The scale-prepared Ru0.8Sb0.2O2 also showed efficient PEMWE performance under industrial conditions.',
        stability: 'PEMWE stability: local file label indicates 500 h at 1 A cm-2. Acidic OER stability was 1100 h at 10 mA cm-2 with low overpotential and ultralow degradation rate.',
        notes: 'Mechanistic point: asymmetric Ru-O-Sb units introduce strong electron delocalization and two-electron Sb redox couples, enabling additional chemical steps during OER and continuous proton transfer. This breaks the scaling-relation limitation while suppressing LOM-associated instability.',
        pdfFileName: '12-Ru0.8Sb0.2O2 -1A-500h-280C.pdf',
        pdfFileSize: '11 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Ta: {
    articles: [
      {
        title: 'Heteroatom dopants overcome the activity-stability trade-off in RuO2 for acidic oxygen evolution',
        journalInfo: 'Nature Communications, 2025, DOI: 10.1038/s41467-025-62036-x',
        publicationYear: '2025',
        publicationId: 'Article 62036-x',
        sampleName: 'Ta/B-RuO2; Ta- and B-codoped nanoporous RuO2 with Ru-O-Ta frameworks and Ru-O-B active sites',
        synthesis: 'Ru-Ta-B precursor ribbons were prepared by melt spinning, then selectively etched by electrochemical corrosion to remove the B-rich phase and transform RuB2 into RuO2. The etched ribbons were annealed in a muffle furnace to obtain a core-shell catalyst containing Ta/B-doped RuO2 shell and Ru-Ta alloy core.',
        activity: 'Acidic OER overpotential of 170 mV at 10 mA cm-2 with a Tafel slope of 44 mV dec-1. In PEMWE, the Ta/B-RuO2 anode reached 1.0 A cm-2 at about 1.6 V and showed polarization up to about 2 A cm-2.',
        stability: 'PEMWE stability: 120 h at 0.2 A cm-2. The reported cell operated around 1.45 V during the 120 h test at 200 mA cm-2, with suppressed Ru dissolution relative to B-RuO2 and RuO2.',
        notes: 'Mechanistic point: Ru-O-Ta frameworks stabilize Ru by mediating bridging oxygen and preferentially replenishing oxygen vacancies, steering OER toward AEM-like behavior. Ru-O-Ta/B sites lower the rate-determining-step barrier. This same article is also listed under B because it is a Ta/B codoped RuO2 system.',
        pdfFileName: '7-Ta-RuO2-0.2A-120h-450C.pdf',
        pdfFileSize: '4.2 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Er: {
    articles: [
      {
        title: 'Lanthanide-regulating Ru-O covalency optimizes acidic oxygen evolution electrocatalysis',
        journalInfo: 'Nature Communications, 2024, DOI: 10.1038/s41467-024-49281-2',
        publicationYear: '2024',
        publicationId: 'Article 49281-2',
        sampleName: 'Er-RuOx; lanthanide-regulated RuOx catalyst',
        synthesis: 'Er-RuOx was prepared by a one-pot glucose-blowing method. Metal precursors, urea, and glucose were heated to form porous foam and annealed at 500 C for 10 h in air to obtain Ln-RuOx; RuO2 was synthesized similarly without lanthanide nitrate.',
        activity: 'Er-RuOx PEMWE device required 1.837 V to reach 3 A cm-2, with reported voltages around 1.590, 1.713, and 1.837 V at 1, 2, and 3 A cm-2. Acidic OER showed improved activity relative to RuO2.',
        stability: 'PEMWE stability: 100 h at 0.5 A cm-2 with degradation rate about 37 uV h-1; the local file name also indicates 100 h class testing at 1 A cm-2. Stability was about 35.5 times higher than RuO2 in the reported comparison.',
        notes: 'Mechanistic point: lanthanide 4f shielding enables continuous tuning of Ru-O covalency. Er gives an optimal volcano-positioned covalency, suppressing lattice oxygen participation and Ru overoxidation while maintaining activity.',
        pdfFileName: '6-Er-RuOx-1A-100h-400C .pdf',
        pdfFileSize: '2.0 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Ir: {
    articles: [
      {
        title: 'Low-iridium stabilized ruthenium oxide anode catalyst for durable proton-exchange membrane water electrolysis',
        journalInfo: 'Nature Nanotechnology, 2025, DOI: 10.1038/s41565-025-02030-y',
        publicationYear: '2025',
        publicationId: 'Article s41565-025-02030-y',
        sampleName: 'Ru6IrOx; Ir-doped RuO2 with Ir:Ru = 1:6 and 14 at.% Ir',
        synthesis: 'RuCl3 and IrCl3.xH2O were dissolved in 3 M HCl, mixed with carbon black for precursor adsorption, dried, annealed in 5% H2/Ar at 800 C for 2 h to form IrRu alloy nanoparticles on carbon, air-annealed at 500 C for 4 h to oxidize and remove carbon, then acid-leached overnight in 1 M HCl, washed and dried. The two-step alloying-to-oxide route was designed to disperse Ir homogeneously inside the RuO2 lattice.',
        activity: 'RDE acidic OER activity was comparable to RuO2, with approximately 240 mV overpotential at 10 mA cm-2 and Tafel slopes around 45-52 mV dec-1. In laboratory PEMWE, Ir-RuOx catalysts showed polarization behaviour similar to RuO2. In a De Nora 25 cm2 PEM electrolyser at 60 C, Ru6IrOx showed nearly identical activity to commercial Ir black up to 1 A cm-2, with slightly higher voltage above 1 A cm-2 despite using roughly one-third of the Ir.',
        stability: 'PEMWE stability: over 1500 h at 2 A cm-2 in laboratory PEMWE with degradation rate of 2.3-2.8 uV h-1. In the 25 cm2 De Nora PEM electrolyser, current was raised to 50 A and held for 1600 h; voltage increased from 1.939 V to 2.000 V in the first 500 h and then decreased to 1.986 V at 1600 h.',
        notes: 'Mechanistic point: DFT and MMC indicate that subsurface Ir, especially first-subsurface Ir, stabilizes neighbouring coordinatively unsaturated Ru sites by increasing Ru vacancy formation energy. XAS supports homogeneous Ir incorporation rather than Ir clustering. Operando Ir L3-edge and Ru K-edge XAS show minimal electronic-structure change during operation.',
        pdfFileName: 's41565-025-02030-y.pdf',
        pdfFileSize: '3.5 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
      {
        title: 'Ultrafast Synthesis of Ir/RuO2 with Enriched Oxygen Vacancies for Durable Acidic Water Electrolysis',
        journalInfo: 'SSRN preprint, 2026, abstract 6055597',
        publicationYear: '2026',
        publicationId: 'SSRN abstract 6055597',
        sampleName: 'Ir/RuO2 via HTS; 1.02 nm Ir clusters anchored on oxygen-vacancy-rich RuO2 nanoparticles',
        synthesis: 'Oxygen-vacancy-rich RuO2 nanoparticles were produced by ultrafast high-temperature shock in about 20 s, followed by wet-chemistry deposition of Ir clusters. The process formed a heterostructured Ir/RuO2 catalyst with stable Ru-O-Ir interfaces.',
        activity: 'Acidic OER overpotential of 150 mV at 10 mA cm-2. PEMWE delivered 1 A cm-2 at about 1.60 V at 60 C.',
        stability: 'PEMWE stability: 100 h at 1 A cm-2. Acidic OER electrolyte stability exceeded 500 h in 0.5 M H2SO4.',
        notes: 'Mechanistic point: oxygen vacancies and interfacial Ru-O-Ir charge transfer promote an AEM-like pathway and suppress Ru overoxidation. Because the PDF is marked as a preprint and not peer reviewed, this entry should be treated as lower-confidence than the journal-published Ir article.',
        pdfFileName: '15.Ir:RuO2 350C 120h 1A.pdf',
        pdfFileSize: '4.7 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Re: {
    articles: [
      {
        title: 'Dynamic rhenium dopant boosts ruthenium oxide for durable oxygen evolution',
        journalInfo: 'Nature Communications, 2023, DOI: 10.1038/s41467-023-35913-6',
        publicationYear: '2023',
        publicationId: 'Article 35913-6',
        sampleName: 'Re0.06Ru0.94O2; dynamic Re-doped RuO2',
        synthesis: 'Re0.06Ru0.94O2 was synthesized by a molten-salt method. NaNO3 and NaReO4 were mixed in a porcelain crucible and heated to 360 C for 10 min; RuCl3.xH2O was then added and held for 5 min. The product was cooled, washed with deionized water to remove salts, and collected by vacuum filtration. Re loading was tuned by changing the amount of NaReO4.',
        activity: 'Acidic OER in O2-saturated 0.1 M HClO4 showed improved activity relative to RuO2, with a Tafel slope of about 45.5 mV dec-1 and high mass activity of 500 A gcat-1 or 7811 A gRe-Ru-1. The paper is primarily an acidic OER mechanistic study rather than a PEMWE single-cell demonstration.',
        stability: 'Acidic OER stability: 200 h at 10 mA cm-2 on carbon paper with 0.2 mgcat cm-2 loading. The potential of Re0.06Ru0.94O2 remained steady, whereas RuO2 decayed within about 19 h. No PEMWE device durability was identified in the main extracted text.',
        notes: 'Mechanistic point: Re acts as a dynamic dopant rather than a static electron-withdrawing substituent. Operando XAS indicates Re accepts electrons at the on-site potential to activate Ru sites, then donates electrons back at high overpotential to suppress Ru dissolution. DEMS, XAS, and DFT support a shift toward AEM, lower oxygen-intermediate adsorption energies, and reduced LOM-driven Ru overoxidation.',
        pdfFileName: 'Re-doped RuOx-200h-360C.pdf',
        pdfFileSize: '2.9 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Pb: {
    articles: [
      {
        title: 'Pinning effect of lattice Pb suppressing lattice oxygen reactivity of Pb-RuO2 enables stable industrial-level electrolysis',
        journalInfo: 'Nature Communications, 2024, DOI: 10.1038/s41467-024-53905-y',
        publicationYear: '2024',
        publicationId: 'Article 53905-y',
        sampleName: 'Pb-RuO2; lattice Pb incorporated into RuO2',
        synthesis: 'Pb-RuO2 was prepared by a one-pot glucose-blowing method. A porous foam containing homogeneously dispersed Ru and Pb ions was first obtained, then calcined in air to form Pb-RuO2. Pure RuO2 was synthesized by the same process without Pb.',
        activity: 'Acidic OER showed low overpotential and improved kinetics relative to home-made and commercial RuO2; the extracted figure text indicates approximately 21 mV decay over 1000 h in acidic OER. PEMWE performance was evaluated at industrial-level current.',
        stability: 'PEMWE stability: 100 h at 1 A cm-2 with low degradation rate of about 17 uV h-1 according to the abstract/file label. Acidic OER stability also showed very small decay over 1000 h.',
        notes: 'Mechanistic point: large, acid-resistant lattice Pb pins oxygen-atom migration channels, reduces lattice oxygen reactivity, lowers Ru-O covalency through 6s-2p-4d orbital hybridization, and suppresses Ru overoxidation. The article frames this as a lattice-oxygen-reactivity control strategy for PEMWE durability.',
        pdfFileName: '13-Pb-RuO2-1A-100h-500C.pdf',
        pdfFileSize: '2.8 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
};

const mergeParsedArticles = (symbol, newArticles) => ({
  articles: [
    ...((window.PEMWE_AI_ENTRIES[symbol] && window.PEMWE_AI_ENTRIES[symbol].articles) || []),
    ...newArticles,
  ],
});

window.PEMWE_AI_ENTRIES = {
  ...window.PEMWE_AI_ENTRIES,
  B: mergeParsedArticles('B', [
    {
      title: 'Motivating Ru-bri site of RuO2 by boron doping toward high performance acidic and neutral oxygen evolution',
      journalInfo: 'Nano Research, 2022, DOI: 10.1007/s12274-022-4337-z',
      publicationYear: '2022',
      publicationId: 'DOI 10.1007/s12274-022-4337-z',
      sampleName: 'B-RuO2; boron-doped RuO2 with activated bridging oxygen sites',
      synthesis: 'Boron-doped RuO2 was prepared to introduce B into the RuO2 lattice/surface and motivate bridging oxygen sites for proton-coupled OER steps. The extracted text emphasizes boron doping as the structural/electronic modifier for Ru-bri sites.',
      activity: 'Acidic OER overpotential of about 200 mV at 10 mA cm-2 in 0.5 M H2SO4. The catalyst also showed high performance under neutral OER conditions.',
      stability: 'Acidic/neutral OER stability was reported as superior to commercial RuO2. No PEMWE single-cell durability was identified from the extracted text.',
      notes: 'Mechanistic point: B doping activates Ru bridging oxygen sites, facilitating proton-transfer/deprotonation steps and improving acidic/neutral OER kinetics. Treat as acidic OER evidence rather than PEMWE device evidence.',
      pdfFileName: 'Motivating Ru-bri site of RuO2 by boron doping toward high performance acidic and neutral oxygen evolution.pdf',
      pdfFileSize: '2.2 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  C: mergeParsedArticles('C', [
    {
      title: 'Single-site Pt-doped RuO2 hollow nanospheres with interstitial C for high-performance acidic overall water splitting',
      journalInfo: 'Science Advances, 2022',
      publicationYear: '2022',
      publicationId: 'Science Advances 8, eabl9271',
      sampleName: 'SS Pt-RuO2 HNSs with interstitial C; single-site Pt-doped RuO2 hollow nanospheres',
      synthesis: 'PtRuSe hollow nanospheres were synthesized hydrothermally and then treated in air at 300 C for 10 h to obtain single-site Pt-doped RuO2 hollow nanospheres with interstitial carbon.',
      activity: 'In 0.5 M H2SO4 acidic overall water splitting, the catalyst required cell voltages of about 1.49, 1.59, and 1.65 V at 10, 50, and 100 mA cm-2, respectively.',
      stability: 'PEM electrolyzer stability: 100 h at 100 mA cm-2. The work reports improved acidic overall-water-splitting durability relative to undoped RuO2.',
      notes: 'Mechanistic point: isolated Pt sites and interstitial C stabilize RuO2, lower OER energy barriers, and suppress acidic deactivation. This article is also listed under Pt because the functional dopant is Pt.',
      pdfFileName: 'Single-site Pt-doped RuO2 hollow nanosphereswith interstitial C for high-performance acidic overallwater splitting.pdf',
      pdfFileSize: '4.5 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Co: mergeParsedArticles('Co', [
    {
      title: 'Revealing the pH-universal electrocatalytic activity of Co-doped RuO2 toward the water oxidation reaction',
      journalInfo: 'ACS Applied Materials & Interfaces, 2022, 14, 1077-1091, DOI: 10.1021/acsami.1c20752',
      publicationYear: '2022',
      publicationId: '14, 1077-1091',
      sampleName: 'Co-RuO2; cobalt-doped rutile RuO2',
      synthesis: 'Co ions were doped into rutile RuO2 to form a rigid Co-RuO2 structural entity. The extracted text emphasizes Co incorporation as a route to resist Ru dissolution and acid corrosion across pH conditions.',
      activity: 'OER overpotentials at 10 mA cm-2 were about 328 mV in acidic electrolyte, 453 mV in neutral electrolyte, 470 mV near-neutral electrolyte, and 238 mV in alkaline electrolyte.',
      stability: 'Stability: 24 h continuous testing across acidic, neutral, near-neutral, and alkaline media with no obvious degradation reported. No PEMWE device durability was identified.',
      notes: 'Mechanistic point: Co doping reinforces the rutile RuO2 framework and improves resistance to Ru dissolution under broad pH operation. Treat as pH-universal OER evidence rather than PEMWE single-cell evidence.',
      pdfFileName: 'madhu-et-al-2021-revealing-the-ph-universal-electrocatalytic-activity-of-co-doped-ruo2-toward-the-water-oxidation.pdf',
      pdfFileSize: '6.3 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Si: mergeParsedArticles('Si', [
    {
      title: 'Locking the lattice oxygen in RuO2 to stabilize highly active Ru sites in acidic water oxidation',
      journalInfo: 'Nature Communications, 2024, DOI: 10.1038/s41467-024-46815-6',
      publicationYear: '2024',
      publicationId: 'Article 46815-6',
      sampleName: 'Si-RuO2-0.1; interstitial Si-doped RuO2',
      synthesis: 'An interstitial silicon-doping strategy was used to incorporate Si into RuO2 and stabilize highly active Ru sites while suppressing lattice oxygen oxidation. The extracted text identifies Si-RuO2-0.1 as the representative catalyst.',
      activity: 'Acidic OER overpotential of 226 mV at 10 mA cm-2.',
      stability: 'Acidic OER stability: 800 h with a negligible degradation rate of about 52 uV h-1. No PEMWE single-cell durability was identified from the extracted text.',
      notes: 'Mechanistic point: interstitial Si weakens/locks lattice oxygen activity, suppressing the DEMS-detected lattice-oxygen-oxidation pathway by about 95% relative to commercial RuO2 and improving Ru-site stability.',
      pdfFileName: 'Locking the lattice oxygen in RuO2 to stabilize highly active Ru sites in acidic water oxidation.pdf',
      pdfFileSize: '2.7 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Ti: mergeParsedArticles('Ti', [
    {
      title: 'Doping Ti into RuO2 to accelerate bridged-oxygen-assisted deprotonation for acidic oxygen evolution',
      journalInfo: 'Advanced Materials, 2024, DOI: 10.1002/adma.202411709',
      publicationYear: '2024',
      publicationId: 'Article 2411709',
      sampleName: 'RuTiOx; Ti-doped RuO2 solid solution',
      synthesis: 'RuTiOx solid-solution catalyst was produced by introducing Ti into RuO2, with hydrothermal restructuring and rutile/anatase oxide phases indicated in the extracted text.',
      activity: 'Acidic OER overpotential of 198 mV at 10 mA cm-2 with improved deprotonation kinetics through bridging oxygen sites.',
      stability: 'Acidic OER stability: over 1400 h at 50 mA cm-2 and over 700 h at 200 mA cm-2. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Ti creates/modulates bridged oxygen proton-acceptor sites, accelerating oxo-intermediate deprotonation through an AEM-like route and suppressing LOM-driven Ru deactivation.',
      pdfFileName: 'Advanced Materials - 2024 - Hu - Doping Ti into RuO2 to Accelerate Bridged-Oxygen-Assisted Deprotonation for Acidic Oxygen.pdf',
      pdfFileSize: '3.9 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Cr: mergeParsedArticles('Cr', [
    {
      title: 'Chromium-ruthenium oxide solid solution electrocatalyst for highly efficient oxygen evolution reaction in acidic media',
      journalInfo: 'Nature Communications, 2019, 10, 162, DOI: 10.1038/s41467-018-08144-3',
      publicationYear: '2019',
      publicationId: '10, 162',
      sampleName: 'Cr0.6Ru0.4O2; chromium-ruthenium oxide solid solution',
      synthesis: 'RuCl3 was loaded into MIL-101(Cr), followed by annealing in air between about 400 and 650 C to form Cr-Ru-O solid-solution powders.',
      activity: 'Acidic OER overpotential of 178 mV at 10 mA cm-2 in 0.5 M H2SO4.',
      stability: 'Acidic OER stability: 10 h chronopotentiometry at 10 mA cm-2. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Cr acts as a promoter in the Ru oxide solid solution, tuning the Ru electronic environment and improving both activity and short-term acidic stability.',
      pdfFileName: 'Chromium-ruthenium oxide solid solution electrocatalyst for highly efficient oxygen evolution reaction in acidic media.pdf',
      pdfFileSize: '3.7 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Cr dopant mediates hydroxyl spillover on RuO2 for high-efficiency proton exchange membrane electrolysis',
      journalInfo: 'Nature Communications, 2024, DOI: 10.1038/s41467-024-51871-z',
      publicationYear: '2024',
      publicationId: 'Article 51871-z',
      sampleName: 'Cr0.2Ru0.8O2-x; Cr-doped RuO2 with oxygen vacancies',
      synthesis: 'Cr-doped rutile RuO2 with oxygen vacancies was synthesized as Cr0.2Ru0.8O2-x. The extracted article text frames the design around Cr-mediated hydroxyl spillover and oxygen-vacancy-rich RuO2.',
      activity: 'Acidic OER overpotential of 170 mV at 10 mA cm-2.',
      stability: 'Acidic OER stability: over 2000 h in acidic media. PEMWE stability: over 200 h at ampere-level current density and 60 C.',
      notes: 'Mechanistic point: Cr dopants mediate hydroxyl spillover on RuO2, balancing AEM/LOM behavior by promoting active oxygen transfer while improving Ru-site durability under PEMWE-relevant current.',
      pdfFileName: 'Cr dopant mediates hydroxyl spillover on RuO2 for high-efficiency proton exchange membrane electrolysis.pdf',
      pdfFileSize: '21.6 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Mn: mergeParsedArticles('Mn', [
    {
      title: 'Mn-doped RuO2 as superior pH-universal electrocatalyst for oxygen evolution reaction',
      journalInfo: 'International Journal of Hydrogen Energy, 2024, DOI: 10.1016/j.ijhydene.2024.06.087',
      publicationYear: '2024',
      publicationId: 'DOI 10.1016/j.ijhydene.2024.06.087',
      sampleName: 'Mn0.1Ru0.9O2; Mn-doped RuO2',
      synthesis: 'Mn was doped into RuO2 to form Mn0.1Ru0.9O2. The extracted text emphasizes electron redistribution from low-valence Mn and improved stability across pH conditions.',
      activity: 'OER overpotential at 10 mA cm-2: 224 mV in acidic electrolyte, 376 mV in neutral electrolyte, and 231 mV in alkaline electrolyte.',
      stability: 'Stability: 24 h continuous testing in acidic, neutral, and alkaline media. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Mn doping redistributes charge around Ru-O sites and may suppress noble-metal oxide dissolution, giving pH-universal OER stability but only short-duration evidence.',
      pdfFileName: 'Mn-doped RuO2 as superior pH-universal electrocatalyst for oxygen evolution reaction.pdf',
      pdfFileSize: '5.4 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Mn-doped Ru/RuO2 nanoclusters@CNT with strong metal-support interaction for efficient water splitting in acidic media',
      journalInfo: 'Composites Part B: Engineering, 2022, DOI: 10.1016/j.compositesb.2022.110013',
      publicationYear: '2022',
      publicationId: 'Article 110013',
      sampleName: 'Mn-Ru/RuO2@CNT; Mn-doped Ru/RuO2 nanoclusters on CNT',
      synthesis: 'M-Ru/RuO2@CNT catalysts (M = Mn, Cd, Cu) were synthesized using heteroatom doping and strong metal-support-interaction strategies to form ultrasmall Ru/RuO2 nanoclusters on carbon nanotubes.',
      activity: 'In 0.5 M H2SO4, Mn-Ru/RuO2@CNT showed OER overpotential of 177 mV and HER overpotential of 30 mV at 10 mA cm-2. Acidic overall water splitting reached 10 and 100 mA cm-2 at about 1.43 and 1.51 V.',
      stability: 'Acidic overall water splitting stability: 100 h at 100 mA cm-2. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Mn doping changes electronic structure through charge redistribution and increases Ru vacancy formation energy, while CNT support helps suppress aggregation and dissolution.',
      pdfFileName: 'Mn-doped RuRuO2 nanoclusters@CNT with strong metal-support interaction for efficient water splitting in acidic media.pdf',
      pdfFileSize: '4.7 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Zn: mergeParsedArticles('Zn', [
    {
      title: 'Interface and electronic structure regulation of RuO2 through Ru/RuO2 heterointerface construction and Zn atom-doping for high-performance overall water splitting in both alkaline and acidic media',
      journalInfo: 'Advanced Functional Materials, 2024, DOI: 10.1002/adfm.202409306',
      publicationYear: '2024',
      publicationId: 'Article 2409306',
      sampleName: 'Ru/ZnRuO2; Zn-doped Ru/RuO2 heterostructure',
      synthesis: 'Zn-BTC MOF was prepared at room temperature, Ru3+ was introduced by ion exchange to form RuZn-BTC, and the precursor was annealed in air at 300 C for 4 h to obtain ultrasmall porous polyhedral Ru/ZnRuO2.',
      activity: 'OER overpotential of 184 mV at 10 mA cm-2 in 0.5 M H2SO4; HER overpotential of 35 mV at 10 mA cm-2 in 1.0 M KOH. Overall water splitting cell voltages were 1.540 and 1.567 V at 10 mA cm-2 in acidic and alkaline media.',
      stability: 'Overall water splitting stability: over 220 h in acidic media and over 100 h in alkaline media. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Zn doping and Ru/RuO2 heterointerfaces regulate electronic structure, expose defects, and combine Ru metallic HER activity with RuO2 OER activity.',
      pdfFileName: 'Adv Funct Materials - 2024 - Zhang - Interface and Electronic Structure Regulation of RuO2 through Ru RuO2 Heterointerface.pdf',
      pdfFileSize: '7.6 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Construction of Zn-doped RuO2 nanowires for efficient and stable water oxidation in acidic media',
      journalInfo: 'Nature Communications, 2023, DOI: 10.1038/s41467-023-38213-1',
      publicationYear: '2023',
      publicationId: 'Article 38213-1',
      sampleName: 'Zn-doped RuO2 nanowires',
      synthesis: 'Zn-doped RuO2 nanowires were constructed to combine Zn lattice doping with high-aspect-ratio RuO2 morphology, increasing exposed active sites and improving acidic OER durability.',
      activity: 'Acidic OER overpotentials of 173, 304, and 373 mV at 10, 500, and 1000 mA cm-2, respectively.',
      stability: 'Acidic OER stability: 1000 h at 10 mA cm-2. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Zn doping modulates Ru electronic structure/defects, while nanowire morphology improves site exposure and high-current OER performance.',
      pdfFileName: 'Construction of Zn-doped RuO2 nanowires for efficient and stable water oxidation in acidic media.pdf',
      pdfFileSize: '2.9 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Surface evolution of Zn doped-RuO2 under different etching methods towards acidic oxygen evolution',
      journalInfo: 'Journal of Materials Chemistry A, 2022, DOI: 10.1039/d2ta03527h',
      publicationYear: '2022',
      publicationId: 'DOI 10.1039/d2ta03527h',
      sampleName: 'E-Zn-RuO2; electrochemically etched Zn-doped RuO2',
      synthesis: 'Zn-BTC was synthesized from trimesic acid and zinc acetate, Ru-Zn-BTC was obtained by Ru3+ ion exchange, and Zn-RuO2 was produced by air calcination at 300 C for 4 h. E-Zn-RuO2 was then formed by electrochemical LSV etching.',
      activity: 'Acidic OER overpotential of 190 mV at 10 mA cm-2 for E-Zn-RuO2.',
      stability: 'Acidic OER stability: over 60 h at 10 mA cm-2, compared with about 15-20 h for chemically etched Zn-RuO2 references.',
      notes: 'Mechanistic point: electrochemical etching induces pre-oxidation and irreversible surface reconstruction, leaving a stable active surface and residual Zn-modulated Ru sites.',
      pdfFileName: 'Surface evolution of Zn doped-RuO2 under different etching methods towards acidic oxygen evolution.pdf',
      pdfFileSize: '1.9 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Pd: mergeParsedArticles('Pd', [
    {
      title: 'Construction of Pd-doped RuO2 nanosheets for efficient and stable acidic water oxidation',
      journalInfo: 'Green Energy & Environment, 2023, DOI: 10.1016/j.gee.2023.12.003',
      publicationYear: '2023',
      publicationId: 'DOI 10.1016/j.gee.2023.12.003',
      sampleName: 'Pd0.08Ru0.92O2; Pd-doped RuO2 nanosheets',
      synthesis: 'Pd-doped RuO2 nanosheets were constructed as a two-dimensional RuO2-based catalyst, using Pd to modulate Ru electronic structure and nanosheet morphology to increase exposed active sites.',
      activity: 'Acidic OER overpotential of about 204 mV at 10 mA cm-2.',
      stability: 'PEM electrolyzer stability: nearly 130 h operation at 200 mA cm-2 using Pd0.08Ru0.92O2 as the anode. CV durability showed only about 5 mV overpotential change after 8000 cycles.',
      notes: 'Mechanistic point: electron transfer from Pd to Ru suppresses Ru overoxidation and dissolution, while the 2D nanosheet structure improves utilization of active Ru sites.',
      pdfFileName: 'Construction of Pd-doped RuO2 nanosheets for efficient and stable acidic water oxidation.pdf',
      pdfFileSize: '2.6 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Mo: mergeParsedArticles('Mo', [
    {
      title: 'Mo-doped mesoporous RuO2 spheres as high-performance acidic oxygen evolution reaction electrocatalysts',
      journalInfo: 'Small, 2024, 20, 2305889, DOI: 10.1002/smll.202305889',
      publicationYear: '2024',
      publicationId: '20, 2305889',
      sampleName: 'Mo0.15-RuO2; Mo-doped mesoporous RuO2 spheres',
      synthesis: 'Mo-doped mesoporous RuO2 spheres were synthesized using ordered mesoporous carbon spheres as the template, followed by impregnation and post-calcination; the carbon template was removed during calcination.',
      activity: 'Acidic OER overpotential of 147 mV at 10 mA cm-2; overpotentials of 221 and 277 mV at 100 and 200 mA cm-2, respectively.',
      stability: 'Long-term acidic OER durability was reported, but the extracted text did not give a PEMWE single-cell durability metric.',
      notes: 'Mechanistic point: Mo doping suppresses RuO2 nanoparticle aggregation, tunes Ru-O covalency, and the mesoporous spherical morphology increases accessible active-site density.',
      pdfFileName: 'Small - 2023 - Zhang - Mo-Doped Mesoporous RuO2 Spheres as High-Performance Acidic Oxygen Evolution Reaction.pdf',
      pdfFileSize: '4.5 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Tuning electron correlations of RuO2 by co-doping of Mo and Ce for boosting electrocatalytic water oxidation in acidic media',
      journalInfo: 'Applied Catalysis B: Environmental, 2021, 298, 120528, DOI: 10.1016/j.apcatb.2021.120528',
      publicationYear: '2021',
      publicationId: '298, 120528',
      sampleName: 'Ru3MoCeOx; Mo/Ce co-doped RuO2',
      synthesis: 'Mo and Ce with large ionic radii were incorporated into RuO2 to redistribute electron correlations around Ru-O bonds and form Ru3MoCeOx.',
      activity: 'Acidic OER overpotential of 164 mV at 10 mA cm-2 and mass activity of 1469.5 A g-1 at 1.53 V vs RHE.',
      stability: 'Acidic OER stability: 100 h at 100 mA cm-2. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Mo/Ce co-doping tunes Ru-O electronic correlation and intermediate energetics, promoting acidic OER activity and durability. This article is also listed under Ce.',
      pdfFileName: 'Tuning electron correlations of RuO2 by co-doping of Mo and Ce for boosting electrocatalytic water oxidation in acidic media.pdf',
      pdfFileSize: '8.6 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Nb: mergeParsedArticles('Nb', [
    {
      title: 'Eliminating over-oxidation of ruthenium oxides by niobium for highly stable electrocatalytic oxygen evolution in acidic media',
      journalInfo: 'Joule, 2023, 7, 558-573, DOI: 10.1016/j.joule.2023.02.012',
      publicationYear: '2023',
      publicationId: '7, 558-573',
      sampleName: 'Nb0.1Ru0.9O2; Nb-incorporated RuO2',
      synthesis: 'Insoluble Nb was incorporated into RuO2 as monodispersed Nb dopants to form Nb0.1Ru0.9O2, creating strong Nb-O bonds and weakening Ru-O overoxidation pathways.',
      activity: 'Acidic OER overpotential of 204 mV. The catalyst was designed for high-current acidic OER and PEM electrolyzer operation.',
      stability: 'Acidic OER stability: 360 h at 200 mA cm-2 with an ultralow degradation rate. PEM electrolyzer stability: 100 h at 300 mA cm-2.',
      notes: 'Mechanistic point: Nb donates electron density to Ru and forms stable Nb5+-O motifs, suppressing high-valence soluble Ru formation and overoxidation while maintaining oxygen-intermediate adsorption.',
      pdfFileName: 'Nb-stabilized RuOx-0.3A-100h 400Cpdf',
      pdfFileSize: '6.2 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  La: mergeParsedArticles('La', [
    {
      title: 'La-RuO2 nanocrystals with efficient electrocatalytic activity for overall water splitting in acidic media: synergistic effect of La doping and oxygen vacancy',
      journalInfo: 'Chemical Engineering Journal, 2022, 439, 135699, DOI: 10.1016/j.cej.2022.135699',
      publicationYear: '2022',
      publicationId: '439, 135699',
      sampleName: 'La-doped RuO2 nanocrystals with oxygen vacancies',
      synthesis: 'La-doped RuO2 nanocrystals were prepared by a hydrothermal process followed by annealing, combining heteroatom La doping with oxygen-vacancy generation.',
      activity: 'Acidic overall-water-splitting catalyst with reported OER overpotential of 208 mV and HER overpotential of 71 mV at 10 mA cm-2.',
      stability: 'Durability was reported for acidic overall water splitting/OER, but no PEMWE single-cell durability was identified from the extracted text.',
      notes: 'Mechanistic point: La doping and oxygen vacancies synergistically modulate RuO2 electronic structure, improving acidic OER/HER bifunctional performance.',
      pdfFileName: 'La-RuO2 nanocrystals with efficient electrocatalytic activity for overall water splitting in acidic media Synergistic effect of La doping and oxygen vacancy.pdf',
      pdfFileSize: '8.3 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Rh: mergeParsedArticles('Rh', [
    {
      title: 'Unraveling oxygen vacancy site mechanism of Rh-doped RuO2 catalyst for long-lasting acidic water oxidation',
      journalInfo: 'Nature Communications, 2023, DOI: 10.1038/s41467-023-37008-8',
      publicationYear: '2023',
      publicationId: 'Article 37008-8',
      sampleName: 'Rh-RuO2; Rh-doped RuO2 with surface oxygen vacancies',
      synthesis: 'Rh doping and surface oxygen vacancies were combined to create Ru-O-Rh active sites in Rh-RuO2.',
      activity: 'Acidic OER overpotential of 161 mV at 10 mA cm-2 with high activity retention.',
      stability: 'Long-lasting acidic water oxidation was reported, including high activity retention from quasi in situ/operando evidence. No PEMWE single-cell durability was identified from the extracted text.',
      notes: 'Mechanistic point: Rh doping plus oxygen vacancies induces an oxygen-vacancy-site mechanism coupled with LOM-like participation, optimizing the *O formation step and improving acidic durability.',
      pdfFileName: 'Unraveling oxygen vacancy site mechanism of Rh-doped RuO2 catalyst for long-lasting acidic water oxidation.pdf',
      pdfFileSize: '2.5 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  In: mergeParsedArticles('In', [
    {
      title: 'Oxygen vacancy-electron polarons featured InSnRuO2 oxides: orderly and concerted active sites for efficient PEMWE',
      journalInfo: 'Advanced Materials, 2024, DOI: 10.1002/adma.202414579',
      publicationYear: '2024',
      publicationId: 'Article 2414579',
      sampleName: 'InSnRuO2; In/Sn/Ru rutile oxide with oxygen-vacancy electron polarons',
      synthesis: 'Rutile InSnRuO2 oxides were fabricated by in situ isomorphic substitution, using trivalent In as oxygen-vacancy generators with adjacent Sn/Ru metal ions stabilizing polaronic active sites.',
      activity: 'Acidic water oxidation overpotential of 183 mV vs RHE and Ru mass activity of 103.02 A mgRu-1.',
      stability: 'PEMWE stability: 200 h at 50 mA cm-2 with a low, nearly unchanged cell potential of about 1.56 V. Accelerated PEMWE testing showed little voltage increase when current increased from 1 to 5 A cm-2.',
      notes: 'Mechanistic point: self-trapped oxygen-vacancy electron polarons lower entropy/enthalpy and increase lattice-atom diffusion barriers, suppressing Ru leaching. This article is also listed under Sn.',
      pdfFileName: 'Advanced Materials - 2024 - Sun - Oxygen Vacancy-Electron Polarons Featured InSnRuO2 Oxides  Orderly and Concerted.pdf',
      pdfFileSize: '10.2 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Sn: mergeParsedArticles('Sn', [
    {
      title: 'Oxygen vacancy-electron polarons featured InSnRuO2 oxides: orderly and concerted active sites for efficient PEMWE',
      journalInfo: 'Advanced Materials, 2024, DOI: 10.1002/adma.202414579',
      publicationYear: '2024',
      publicationId: 'Article 2414579',
      sampleName: 'InSnRuO2; In/Sn/Ru rutile oxide with oxygen-vacancy electron polarons',
      synthesis: 'Rutile InSnRuO2 oxides were fabricated by in situ isomorphic substitution, using trivalent In as oxygen-vacancy generators and Sn/Ru cations to stabilize complementary electronic structures.',
      activity: 'Acidic water oxidation overpotential of 183 mV vs RHE and Ru mass activity of 103.02 A mgRu-1.',
      stability: 'PEMWE stability: 200 h at 50 mA cm-2 with a low, nearly unchanged cell potential of about 1.56 V. Accelerated PEMWE testing showed little voltage increase when current increased from 1 to 5 A cm-2.',
      notes: 'Mechanistic point: Sn helps maintain rutile structural compatibility and defect tolerance, while In generates oxygen-vacancy electron polarons. This article is also listed under In.',
      pdfFileName: 'Advanced Materials - 2024 - Sun - Oxygen Vacancy-Electron Polarons Featured InSnRuO2 Oxides  Orderly and Concerted.pdf',
      pdfFileSize: '10.2 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Ultra-small Sn-RuO2 nanoparticles supported on N-doped carbon polyhedra for highly active and durable oxygen evolution reaction in acidic media',
      journalInfo: 'Chemical Engineering Journal, 2021, 409, 128155, DOI: 10.1016/j.cej.2020.128155',
      publicationYear: '2021',
      publicationId: '409, 128155',
      sampleName: 'Sn-RuO2@NPC; Sn-doped RuO2 nanoparticles on N-doped carbon polyhedra',
      synthesis: 'Sn-doped RuO2 nanoparticles were supported on N-doped carbon polyhedra derived from ZIF-8 through dipping and annealing.',
      activity: 'Acidic OER overpotential of 178 mV at 10 mA cm-2.',
      stability: 'Acidic OER stability: 150 h in acidic media. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Sn doping and nanoscale dispersion on N-doped carbon polyhedra improve RuO2 utilization and acidic OER durability.',
      pdfFileName: 'Ultra-small Sn-RuO2 nanoparticles supported on N-doped carbon polyhedra for highly active and durable oxygen evolution reaction in acidic media.pdf',
      pdfFileSize: '6.5 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Pt: mergeParsedArticles('Pt', [
    {
      title: 'Single-site Pt-doped RuO2 hollow nanospheres with interstitial C for high-performance acidic overall water splitting',
      journalInfo: 'Science Advances, 2022',
      publicationYear: '2022',
      publicationId: 'Science Advances 8, eabl9271',
      sampleName: 'SS Pt-RuO2 HNSs with interstitial C; single-site Pt-doped RuO2 hollow nanospheres',
      synthesis: 'PtRuSe hollow nanospheres were synthesized hydrothermally and then treated in air at 300 C for 10 h to obtain single-site Pt-doped RuO2 hollow nanospheres with interstitial carbon.',
      activity: 'In 0.5 M H2SO4 acidic overall water splitting, the catalyst required cell voltages of about 1.49, 1.59, and 1.65 V at 10, 50, and 100 mA cm-2, respectively.',
      stability: 'PEM electrolyzer stability: 100 h at 100 mA cm-2. The work reports improved acidic overall-water-splitting durability relative to undoped RuO2.',
      notes: 'Mechanistic point: isolated Pt sites stabilize RuO2 and reduce OER energy barriers, while interstitial C contributes to structural/electronic stabilization. This article is also listed under C.',
      pdfFileName: 'Single-site Pt-doped RuO2 hollow nanosphereswith interstitial C for high-performance acidic overallwater splitting.pdf',
      pdfFileSize: '4.5 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Ce: mergeParsedArticles('Ce', [
    {
      title: 'Unravel the mechanism of d-orbital modulation and oxygen vacancy in cerium-doped RuO2 catalysts for acidic oxygen evolution reaction',
      journalInfo: 'Applied Surface Science, 2024, 642, 158613, DOI: 10.1016/j.apsusc.2023.158613',
      publicationYear: '2024',
      publicationId: '642, 158613',
      sampleName: 'Ce-RuO2; cerium-doped RuO2',
      synthesis: 'Ce dopants were introduced into RuO2 to modulate the local bonding environment, d-orbital electronic structure, and oxygen-vacancy behavior during acidic OER.',
      activity: 'Acidic OER overpotential of 191 mV at 10 mA cm-2, lower than undoped RuO2 and commercial RuO2 references.',
      stability: 'Durable acidic OER behavior was reported, but no PEMWE single-cell durability was identified from the extracted text.',
      notes: 'Mechanistic point: Ce lowers the density of states near the Fermi level and modulates adsorption of oxygen intermediates, suppressing lattice-oxygen-driven high-valence Ru formation.',
      pdfFileName: 'Unravel the mechanism of d-orbital modulation and oxygen vacancy in cerium-doped RuO2 catalysts for acidic oxygen evolution reaction.pdf',
      pdfFileSize: '7.3 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Tuning electron correlations of RuO2 by co-doping of Mo and Ce for boosting electrocatalytic water oxidation in acidic media',
      journalInfo: 'Applied Catalysis B: Environmental, 2021, 298, 120528, DOI: 10.1016/j.apcatb.2021.120528',
      publicationYear: '2021',
      publicationId: '298, 120528',
      sampleName: 'Ru3MoCeOx; Mo/Ce co-doped RuO2',
      synthesis: 'Mo and Ce with large ionic radii were incorporated into RuO2 to redistribute electron correlations around Ru-O bonds and form Ru3MoCeOx.',
      activity: 'Acidic OER overpotential of 164 mV at 10 mA cm-2 and mass activity of 1469.5 A g-1 at 1.53 V vs RHE.',
      stability: 'Acidic OER stability: 100 h at 100 mA cm-2. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Ce and Mo co-doping tune Ru-O electronic correlation and lower oxygen-intermediate barriers. This article is also listed under Mo.',
      pdfFileName: 'Tuning electron correlations of RuO2 by co-doping of Mo and Ce for boosting electrocatalytic water oxidation in acidic media.pdf',
      pdfFileSize: '8.6 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
  Bi: mergeParsedArticles('Bi', [
    {
      title: 'A Bi-doped RuO2 catalyst for efficient and durable acidic water oxidation',
      journalInfo: 'Chinese Journal of Catalysis, 2023, 55, 182-190, DOI: 10.1016/S1872-2067(23)64554-1',
      publicationYear: '2023',
      publicationId: '55, 182-190',
      sampleName: 'Bi0.15Ru0.85O2; Bi-doped RuO2',
      synthesis: 'RuCl3, BiCl3, PVP, and citric acid were dissolved in a mixed solution, ultrasonicated, transferred to a Teflon-lined autoclave, hydrothermally treated at 200 C, and further processed to obtain Bi-doped RuO2.',
      activity: 'Acidic OER overpotential of 200 mV at 10 mA cm-2.',
      stability: 'Acidic OER stability: over 100 h. No PEMWE single-cell durability was identified.',
      notes: 'Mechanistic point: Bi activates Ru sites and strengthens Bi-Ru electronic interaction, reducing OER energy barriers and avoiding overoxidation of active Ru species.',
      pdfFileName: 'A Bi-doped RuO2 catalyst for efficient and durable acidic water oxidation.pdf',
      pdfFileSize: '2.5 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
    {
      title: 'Phase-engineered Bi-RuO2 single-atom alloy oxide boosting oxygen evolution electrocatalysis in proton exchange membrane water electrolyzer',
      journalInfo: 'Advanced Materials, 2025, DOI: 10.1002/adma.202417777',
      publicationYear: '2025',
      publicationId: 'Article 2417777',
      sampleName: 'Bi-RuO2 SAAO; phase-engineered Bi-RuO2 single-atom alloy oxide',
      synthesis: 'A hexagonal close packed RuBi single-atom alloy was phase-engineered into a Bi-RuO2 single-atom alloy oxide catalyst for acidic OER and PEMWE operation.',
      activity: 'Acidic OER overpotential of 192 mV. PEMWE required about 1.59 V to reach 1.0 A cm-2 under industrial conditions and about 1.94-1.97 V to reach 3.0 A cm-2 at elevated temperature.',
      stability: 'Acidic OER stability: over 650 h at 10 mA cm-2. PEMWE performance was demonstrated under industrial conditions; the extracted text did not give a single fixed durability hour for PEMWE.',
      notes: 'Mechanistic point: Bi improves activity by optimizing electronic density and improves stability by hindering Ru demetallation; operando DEMS/DFT support an AEM-like pathway.',
      pdfFileName: 'Advanced Materials - 2025 - Yang - Phase-Engineered Bi-RuO2 Single-Atom Alloy Oxide Boosting Oxygen Evolution.pdf',
      pdfFileSize: '3.3 MB',
      pdfUploadedAt: '2026-06-23',
      updatedAt: '2026-06-23',
    },
  ]),
};

window.PEMWE_AI_ENTRIES = {
  ...window.PEMWE_AI_ENTRIES,
  Ir: mergeParsedArticles('Ir', [
    {
      title: 'Covalency regulation of Ru-based solid solutions by iridium for durable proton exchange membrane water electrolysis',
      journalInfo: 'Advanced Functional Materials, 2025, DOI: 10.1002/adfm.202506203',
      publicationYear: '2025',
      publicationId: 'Article 2506203',
      sampleName: 'Ru8Ir1Ox; Ir-regulated Ru-based solid solution',
      synthesis: 'Ru-Ir bimetallic oxides with varied Ru/Ir ratios were prepared by a sol-gel method. XRD/Raman/XAFS showed Ir incorporation into rutile RuO2-like solid solutions and weakened Ru-O covalency.',
      activity: 'Acidic OER: Ru8Ir1Ox overpotential 177 mV at 10 mA cm-2 in 0.5 M H2SO4. PEMWE: cell voltage 1.76 V at 3 A cm-2.',
      stability: 'PEMWE device stability: 350 h at 2 A cm-2. Separate acidic OER three-electrode stability: 850 h at 100 mA cm-2 in 0.5 M H2SO4 with degradation rate 0.085 mV h-1.',
      notes: 'Mechanistic point: Ir expands Ru-O bonds, weakens Ru 4d-O 2p hybridization, promotes AEM-like behavior, suppresses lattice oxygen participation and Ru leaching, and avoids corrosion of less stable guest dopants.',
      pdfFileName: 'Adv Funct Materials - 2025 - Du - Covalency Regulation of Ru-Based Solid Solutions by Iridium for Durable Proton Exchange.pdf',
      pdfFileSize: '5.2 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
    {
      title: 'Operando insights into bridging oxygen-driven RuOx lattice collapse and its mitigation strategy for durable industrial PEMWE',
      journalInfo: 'Angewandte Chemie International Edition, 2025, DOI: 10.1002/anie.202520766',
      publicationYear: '2025',
      publicationId: 'Article e202520766',
      sampleName: 'Ru0.9Ir0.1Ox; low-level Ir-doped RuOx',
      synthesis: 'RuOx and low-Ir Ru0.9Ir0.1Ox catalysts were compared under operando PEMWE diagnostics. Ir doping was introduced at low level to stabilize bridging oxygen in the Ru-O framework.',
      activity: 'PEMWE: Ru0.9Ir0.1Ox reached 3 A cm-2 at about 1.74 V under practical operating conditions.',
      stability: 'PEMWE device stability: Ru0.9Ir0.1Ox maintained stable operation for over 500 h at 1 A cm-2. Operando PEMWE-XAS showed RuOx degradation through loss of bridging oxygen; Ir doping increased bridging-oxygen vacancy formation energy and improved structural resilience.',
      notes: 'Mechanistic point: device-level operando Ru K-edge XAS/EXAFS links RuOx failure to irreversible loss of Ru-O and Ru-O-Ru coordination; small Ir incorporation stabilizes the Ru-O bridge network rather than simply lowering activity.',
      pdfFileName: 'Angew Chem Int Ed - 2025 - Xu - Operando Insights into Bridging Oxygen-Driven RuOx Lattice Collapse and its Mitigation.pdf',
      pdfFileSize: '2.8 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  W: mergeParsedArticles('W', [
    {
      title: 'Valence oscillation of Ru active sites for efficient and robust acidic water oxidation',
      journalInfo: 'Advanced Materials, 2023, DOI: 10.1002/adma.202305939',
      publicationYear: '2023',
      publicationId: 'Article 2305939',
      sampleName: '(Ru-W)Ox; inter-doped Ru-W oxide heterostructure',
      synthesis: '(Ru-W)Ox nano-heterostructures were prepared by a sequential two-step approach, beginning with rapid solution combustion growth of Ru-W mixed oxide nanoparticles on carbon cloth.',
      activity: 'Acidic OER: overpotential 170 mV at 10 mA cm-2.',
      stability: 'PEMWE device stability: stable operation for 300 h at 0.5 A cm-2 using (Ru-W)Ox as the anode. Separate acidic electrolyte stability: 300 h in acidic OER testing.',
      notes: 'Mechanistic point: W promotes reversible Ru valence oscillation and helps avoid excessive Ru oxidation under acidic OER, maintaining active Ru sites across a broad potential range.',
      pdfFileName: 'Advanced Materials - 2023 - Deng - Valence Oscillation of Ru Active Sites for Efficient and Robust Acidic Water Oxidation.pdf',
      pdfFileSize: '4.5 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Fe: mergeParsedArticles('Fe', [
    {
      title: 'Ruthenium-based binary alloy with oxide nanosheath for highly efficient and stable acidic water oxidation',
      journalInfo: 'Advanced Materials, 2024, DOI: 10.1002/adma.202312369',
      publicationYear: '2024',
      publicationId: 'Article 2312369',
      sampleName: 'RuFe@CF; Ru-Fe nanoparticles on carbon felt with Ru-based oxide nanosheath',
      synthesis: 'Ru-Fe nanoparticles were loaded on carbon felt by ultrafast Joule heating. During acidic OER, a Ru-based oxide nanosheath formed on the catalyst surface through reconstruction.',
      activity: 'Acidic OER: overpotentials of 188 and 269 mV at 10 and 100 mA cm-2, respectively.',
      stability: 'PEM water electrolyzer device stability: over 250 h at 200 mA cm-2. Separate acidic OER stability: up to 620 h at 10 mA cm-2.',
      notes: 'Mechanistic point: Fe in RuFe lowers OER energy barriers, while the reconstructed oxide nanosheath enhances intrinsic activity and suppresses continuous metal dissolution.',
      pdfFileName: 'Advanced Materials - 2024 - Chen - Ruthenium-Based Binary Alloy with Oxide Nanosheath for Highly Efficient and Stable.pdf',
      pdfFileSize: '4.4 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  V: mergeParsedArticles('V', [
    {
      title: 'Atomically dispersed vanadium-induced Ru-V dual active sites enable exceptional performance for acidic water oxidation',
      journalInfo: 'Angewandte Chemie International Edition, 2024, DOI: 10.1002/anie.202413657',
      publicationYear: '2024',
      publicationId: 'Article e202413657',
      sampleName: 'Vn-RuO2; atomically dispersed V-induced Ru-V dual active sites',
      synthesis: 'Atomically dispersed V species, including O-bridged V dimers, were introduced into RuO2 to form Ru-V dual active sites.',
      activity: 'Acidic OER: overpotential 227 mV at 10 mA cm-2.',
      stability: 'Acidic OER three-electrode stability: 1050 h in acidic electrolyte. No PEMWE device durability was identified from the extracted text.',
      notes: 'Mechanistic point: V-induced Ru-V dual active sites regulate the OER pathway and reduce activity-stability trade-off; operando spectroscopy/DFT indicate optimized Ru-V interaction and improved resistance to Ru overoxidation.',
      pdfFileName: 'Angew Chem Int Ed - 2024 - Qin - Atomically Dispersed Vanadium-Induced Ru V Dual Active Sites Enable Exceptional.pdf',
      pdfFileSize: '2.8 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Mn: mergeParsedArticles('Mn', [
    {
      title: 'Amorphous MnRuOx containing microcrystalline domains for enhanced acidic oxygen-evolution activity and stability',
      journalInfo: 'Angewandte Chemie International Edition, 2024, DOI: 10.1002/anie.202405641',
      publicationYear: '2024',
      publicationId: 'Article e202405641',
      sampleName: 'MnRuOx-300; amorphous MnRuOx with RuO2 microcrystalline regions',
      synthesis: 'MnRuOx catalysts were annealed at different temperatures. MnRuOx-300, prepared at 300 C, contains an optimal amorphous/crystalline heterostructure with RuO2 microcrystalline regions embedded in amorphous MnRuOx.',
      activity: 'Acidic OER: MnRuOx-300 showed superior OER activity versus commercial RuO2; the anode reached 1 A cm-2 at 2.12 V before iR correction and 1.62 V after iR correction in H-type acidic electrolysis configuration.',
      stability: 'Acidic OER high-current stability in H-type electrolysis cell at pH 0 on Ti fiber felt: about 780 h at 100 mA cm-2, 400 h at 200 mA cm-2, 130 h at 500 mA cm-2, and 30 h at 1.0 A cm-2. This is not a membrane-electrode PEMWE durability test.',
      notes: 'Mechanistic point: amorphous/crystalline interfaces increase active defects, shift the d-band center, reduce charge-transfer resistance, and improve high-current acidic OER durability.',
      pdfFileName: 'Angew Chem Int Ed - 2024 - Zhang - Amorphous MnRuOx Containing Microcrystalline for Enhanced Acidic Oxygen-Evolution.pdf',
      pdfFileSize: '7.0 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Sn: mergeParsedArticles('Sn', [
    {
      title: 'Strain-modulated Ru-O covalency in Ru-Sn oxide enabling efficient and stable water oxidation in acidic solution',
      journalInfo: 'Angewandte Chemie International Edition, 2024, DOI: 10.1002/anie.202316029',
      publicationYear: '2024',
      publicationId: 'Article e202316029',
      sampleName: 'RuSnOx; binary Ru-Sn oxide with tensile-strained RuO6 octahedra',
      synthesis: 'A binary Ru-Sn oxide matrix was used to introduce tensile strain into RuO6 octahedra and tune Ru-O covalency.',
      activity: 'Acidic OER in 0.1 M HClO4: overpotential 184 mV at 10 mA cm-2.',
      stability: 'Acidic OER three-electrode stability: at least 150 h at 10 mA cm-2 in 0.1 M HClO4 with negligible potential increase. No PEMWE device durability was identified.',
      notes: 'Mechanistic point: tensile strain weakens Ru-O covalency, suppresses lattice oxygen participation and Ru dissolution, and stabilizes Ru active sites in acidic electrolyte.',
      pdfFileName: 'Angewandte Chemie - 2024 - Xu - Strain-modulated Ru-O Covalency in Ru-Sn Oxide Enabling Efficient and Stable Water.pdf',
      pdfFileSize: '2.5 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Ba: mergeParsedArticles('Ba', [
    {
      title: 'Synergistic co-doping of barium and cobalt enables stable and active RuO2 for acidic water oxidation',
      journalInfo: 'Angewandte Chemie International Edition, 2026, DOI: 10.1002/anie.202521873',
      publicationYear: '2026',
      publicationId: 'Article e202521873',
      sampleName: 'Ba/Co-RuO2; Ba and Co co-doped RuO2',
      synthesis: 'Ba and Co were co-doped into RuO2 to induce lattice strain and electron redistribution, producing Ba/Co-RuO2 for acidic OER and PEMWE operation.',
      activity: 'Acidic OER: overpotential 166 mV at 10 mA cm-2. PEMWE: 3 A cm-2 at 1.87 V.',
      stability: 'PEMWE device stability: over 300 h at 800 mA cm-2. Separate acidic OER stability: over 1500 h at 10 mA cm-2 in 0.5 M H2SO4 with negligible decay.',
      notes: 'Mechanistic point: Ba/Co co-doping suppresses lattice oxygen loss and soluble RuO4 formation by strain/electronic redistribution, promoting AEM while suppressing LOM. This article is also listed under Co.',
      pdfFileName: 'Angewandte Chemie - 2026 - Pei - Synergistic Co-Doping of Barium and Cobalt Enables Stable and Active RuO2 for Acidic Water.pdf',
      pdfFileSize: '5.6 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Co: mergeParsedArticles('Co', [
    {
      title: 'Synergistic co-doping of barium and cobalt enables stable and active RuO2 for acidic water oxidation',
      journalInfo: 'Angewandte Chemie International Edition, 2026, DOI: 10.1002/anie.202521873',
      publicationYear: '2026',
      publicationId: 'Article e202521873',
      sampleName: 'Ba/Co-RuO2; Ba and Co co-doped RuO2',
      synthesis: 'Ba and Co were co-doped into RuO2 to induce lattice strain and electron redistribution, producing Ba/Co-RuO2 for acidic OER and PEMWE operation.',
      activity: 'Acidic OER: overpotential 166 mV at 10 mA cm-2. PEMWE: 3 A cm-2 at 1.87 V.',
      stability: 'PEMWE device stability: over 300 h at 800 mA cm-2. Separate acidic OER stability: over 1500 h at 10 mA cm-2 in 0.5 M H2SO4 with negligible decay.',
      notes: 'Mechanistic point: Co works with Ba to redistribute charge and stabilize RuO2 against lattice oxygen loss and Ru overoxidation. This article is also listed under Ba.',
      pdfFileName: 'Angewandte Chemie - 2026 - Pei - Synergistic Co-Doping of Barium and Cobalt Enables Stable and Active RuO2 for Acidic Water.pdf',
      pdfFileSize: '5.6 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Hf: mergeParsedArticles('Hf', [
    {
      title: 'Engineering lattice distortion in ruthenium oxide enables robust acidic water oxidation',
      journalInfo: 'Advanced Materials, 2025, DOI: 10.1002/adma.202500449',
      publicationYear: '2025',
      publicationId: 'Article 2500449',
      sampleName: 'Na/Hf-RuO2; Na and Hf co-modified RuO2',
      synthesis: 'Na/Hf-RuO2 was synthesized to introduce lattice distortion and tune neighboring Ru-site geometry for direct oxo coupling.',
      activity: 'Acidic OER: overpotential 238 mV at 10 mA cm-2. PEMWE: 1 A cm-2 at 1.646 V and 60 C.',
      stability: 'PEMWE device stability: 85 h at 0.5 A cm-2 and 60 C. The paper attributes the durability to an oxide path mechanism rather than LOM/AEM alone.',
      notes: 'Mechanistic point: Na/Hf-induced lattice distortion optimizes adjacent Ru-site interaction, promotes direct O-O coupling through OPM, and suppresses Ru overoxidation. This article is also listed under Na.',
      pdfFileName: 'Advanced Materials - 2025 - Zhu - Engineering Lattice Distortion in Ruthenium Oxide Enables Robust Acidic Water Oxidation.pdf',
      pdfFileSize: '5.0 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Na: mergeParsedArticles('Na', [
    {
      title: 'Engineering lattice distortion in ruthenium oxide enables robust acidic water oxidation',
      journalInfo: 'Advanced Materials, 2025, DOI: 10.1002/adma.202500449',
      publicationYear: '2025',
      publicationId: 'Article 2500449',
      sampleName: 'Na/Hf-RuO2; Na and Hf co-modified RuO2',
      synthesis: 'Na/Hf-RuO2 was synthesized to introduce lattice distortion and tune neighboring Ru-site geometry for direct oxo coupling.',
      activity: 'Acidic OER: overpotential 238 mV at 10 mA cm-2. PEMWE: 1 A cm-2 at 1.646 V and 60 C.',
      stability: 'PEMWE device stability: 85 h at 0.5 A cm-2 and 60 C. This is a device-level PEMWE test, not only three-electrode acidic OER.',
      notes: 'Mechanistic point: Na/Hf-induced lattice distortion promotes OPM via direct O-O coupling and improves acidic OER durability. This article is also listed under Hf.',
      pdfFileName: 'Advanced Materials - 2025 - Zhu - Engineering Lattice Distortion in Ruthenium Oxide Enables Robust Acidic Water Oxidation.pdf',
      pdfFileSize: '5.0 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  S: mergeParsedArticles('S', [
    {
      title: 'Oxyanion engineering on RuO2 for efficient proton exchange membrane water electrolysis',
      journalInfo: 'Angewandte Chemie International Edition, 2024, DOI: 10.1002/anie.202413653',
      publicationYear: '2024',
      publicationId: 'Article e202413653',
      sampleName: 'Sulfate-anchored RuO2/MoO3; oxyanion-engineered RuO2',
      synthesis: 'A multicomponent catalyst was designed by anchoring sulfate oxyanions on RuO2/MoO3, using MoO3-anchored sulfate to stabilize RuO2 under acidic OER.',
      activity: 'Acidic OER: overpotential 190 mV at 10 mA cm-2.',
      stability: 'PEMWE device stability: 150 h at 500 mA cm-2 using the catalyst as anode. Separate acidic OER stability: 500 h with degradation rate about 20 uV h-1.',
      notes: 'Mechanistic point: sulfate oxyanions reduce *OOH formation energy and suppress both surface Ru loss and lattice oxygen loss. This is an anion/oxyanion modification rather than simple cation doping.',
      pdfFileName: 'Angew Chem Int Ed - 2024 - Duan - Oxyanion Engineering on RuO2 for Efficient Proton Exchange Membrane Water Electrolysis.pdf',
      pdfFileSize: '1.1 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  F: mergeParsedArticles('F', [
    {
      title: 'Fluorine mediates the deprotonation pathway over ruthenium oxide for stable water electrolysis',
      journalInfo: 'Journal of the American Chemical Society, 2026, 148, 10132-10142, DOI: 10.1021/jacs.6c00523',
      publicationYear: '2026',
      publicationId: '148, 10132-10142',
      sampleName: 'F-tuned RuO2 with terminal F and bridging F sites',
      synthesis: 'Fluorine-tuned RuO2 was prepared to introduce terminal fluorine and bridging fluorine sites, targeting proton relay and lattice oxygen stabilization.',
      activity: 'Acidic OER: overpotential 191 mV at 10 mA cm-2. PEMWE: 1000 mA cm-2 at about 1.72 V.',
      stability: 'PEMWE device stability: over 300 h at 1000 mA cm-2 with voltage degradation rate 84 uV h-1. Separate acidic OER stability: maintained 10 mA cm-2 for over 2000 h.',
      notes: 'Mechanistic point: terminal F acts as a proton relay to accelerate deprotonation, while bridging F suppresses lattice oxygen oxidation and Ru dissolution.',
      pdfFileName: 'fluorine-mediates-the-deprotonation-pathway-over-ruthenium-oxide-for-stable-water-electrolysis.pdf',
      pdfFileSize: '7.8 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  B: mergeParsedArticles('B', [
    {
      title: 'Grain boundary-driven synergistic dual-mechanism catalysis in RuO2 for enhancing acidic oxygen evolution reaction activity and stability',
      journalInfo: 'Journal of the American Chemical Society, 2025, DOI: 10.1021/jacs.5c13192',
      publicationYear: '2025',
      publicationId: 'DOI 10.1021/jacs.5c13192',
      sampleName: 'Ni,B-RuOx; grain-boundary-rich Ni/B-modified RuOx',
      synthesis: 'Ni,B-RuOx was engineered with grain-boundary-rich architecture to create separate interfacial and lattice active regions.',
      activity: 'Acidic OER: overpotential 206.8 +/- 1.3 mV at 10 mA cm-2.',
      stability: 'Acidic OER three-electrode stability: over 700 h in 0.5 M H2SO4. PEMWE kinetic analysis was reported, but the extracted text did not provide a fixed device durability time.',
      notes: 'Mechanistic point: interfacial sites optimize AEM oxygen-intermediate adsorption while lattice sites enable controlled LOM participation; this spatial separation improves activity and stability. This article is also listed under Ni.',
      pdfFileName: 'grain-boundary-driven-synergistic-dual-mechanism-catalysis-in-ruo2-for-enhancing-acidic-oxygen-evolution-reaction.pdf',
      pdfFileSize: '10.3 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Ni: mergeParsedArticles('Ni', [
    {
      title: 'Grain boundary-driven synergistic dual-mechanism catalysis in RuO2 for enhancing acidic oxygen evolution reaction activity and stability',
      journalInfo: 'Journal of the American Chemical Society, 2025, DOI: 10.1021/jacs.5c13192',
      publicationYear: '2025',
      publicationId: 'DOI 10.1021/jacs.5c13192',
      sampleName: 'Ni,B-RuOx; grain-boundary-rich Ni/B-modified RuOx',
      synthesis: 'Ni,B-RuOx was engineered with grain-boundary-rich architecture to create separate interfacial and lattice active regions.',
      activity: 'Acidic OER: overpotential 206.8 +/- 1.3 mV at 10 mA cm-2.',
      stability: 'Acidic OER three-electrode stability: over 700 h in 0.5 M H2SO4. PEMWE kinetic analysis was reported, but no fixed device durability time was identified in the extracted text.',
      notes: 'Mechanistic point: Ni/B modification separates AEM-favorable interfacial sites and LOM-active lattice sites, improving RuOx stability. This article is also listed under B.',
      pdfFileName: 'grain-boundary-driven-synergistic-dual-mechanism-catalysis-in-ruo2-for-enhancing-acidic-oxygen-evolution-reaction.pdf',
      pdfFileSize: '10.3 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Ga: mergeParsedArticles('Ga', [
    {
      title: 'p-p orbital hybridization stabilizing lattice oxygen in two-dimensional amorphous RuOx for acidic oxygen evolution',
      journalInfo: 'Angewandte Chemie International Edition, 2025, DOI: 10.1002/anie.202505908',
      publicationYear: '2025',
      publicationId: 'Article e202505908',
      sampleName: 'Ga-RuOx; two-dimensional amorphous Ga-doped RuOx',
      synthesis: 'Amorphous M-RuOx catalysts were prepared by atomic-level mixing of metal acetylacetonates; Ga-RuOx showed a two-dimensional sheet-like amorphous morphology with Ru/Ga ratio controlled near 3/1.',
      activity: 'Acidic OER: Ga doping reduced the overpotential at 10 mA cm-2 by 137 mV relative to undoped RuOx.',
      stability: 'Acidic OER three-electrode stability: 125-fold improvement versus undoped RuOx was reported. No PEMWE device durability was identified from the extracted text.',
      notes: 'Mechanistic point: Ga-O p-p orbital hybridization stabilizes lattice oxygen, suppresses Ru overoxidation, and switches the pathway from LOM toward AEM. The same study also examined Al and In dopants, but Ga was the best performer.',
      pdfFileName: 'Angew Chem Int Ed - 2025 - Mu - p-p Orbital Hybridization Stabilizing Lattice Oxygen in Two-dimensional Amorphous RuOx for.pdf',
      pdfFileSize: '6.8 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Cr: mergeParsedArticles('Cr', [
    {
      title: 'Pourbaix machine learning framework identifies acidic water oxidation catalysts exhibiting suppressed ruthenium dissolution',
      journalInfo: 'Journal of the American Chemical Society, 2024, DOI: 10.1021/jacs.4c01353',
      publicationYear: '2024',
      publicationId: 'DOI 10.1021/jacs.4c01353',
      sampleName: 'Ru0.6Cr0.2Ti0.2O2; Cr/Ti co-doped RuO2 candidate from Pourbaix ML screening',
      synthesis: 'A Pourbaix-ML workflow screened metallic oxides and identified Ru0.6Cr0.2Ti0.2O2; the candidate was then experimentally synthesized and tested for acidic OER.',
      activity: 'Acidic OER: overpotential 267 mV at 100 mA cm-2.',
      stability: 'Acidic OER three-electrode stability: over 200 h at 100 mA cm-2 with overpotential increase rate about 25 uV h-1. No PEMWE device durability was identified.',
      notes: 'Mechanistic point: Ti increases metal-oxygen covalency for stability, while Cr lowers the HOO* formation barrier; in situ XAS and ptychography-STXM showed 20x slower Ru dissolution and over 60% suppression of lattice oxygen participation compared with RuO2. This article is also listed under Ti.',
      pdfFileName: 'abed-et-al-2024-pourbaix-machine-learning-framework-identifies-acidic-water-oxidation-catalysts-exhibiting-suppressed.pdf',
      pdfFileSize: '7.5 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Ti: mergeParsedArticles('Ti', [
    {
      title: 'Pourbaix machine learning framework identifies acidic water oxidation catalysts exhibiting suppressed ruthenium dissolution',
      journalInfo: 'Journal of the American Chemical Society, 2024, DOI: 10.1021/jacs.4c01353',
      publicationYear: '2024',
      publicationId: 'DOI 10.1021/jacs.4c01353',
      sampleName: 'Ru0.6Cr0.2Ti0.2O2; Cr/Ti co-doped RuO2 candidate from Pourbaix ML screening',
      synthesis: 'A Pourbaix-ML workflow screened metallic oxides and identified Ru0.6Cr0.2Ti0.2O2; the candidate was then experimentally synthesized and tested for acidic OER.',
      activity: 'Acidic OER: overpotential 267 mV at 100 mA cm-2.',
      stability: 'Acidic OER three-electrode stability: over 200 h at 100 mA cm-2 with overpotential increase rate about 25 uV h-1. No PEMWE device durability was identified.',
      notes: 'Mechanistic point: Ti increases metal-oxygen covalency and stability, while Cr lowers the HOO* barrier. This article is also listed under Cr.',
      pdfFileName: 'abed-et-al-2024-pourbaix-machine-learning-framework-identifies-acidic-water-oxidation-catalysts-exhibiting-suppressed.pdf',
      pdfFileSize: '7.5 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
  Zn: mergeParsedArticles('Zn', [
    {
      title: 'Designing 3d transition metal cation-doped MRuOx as durable acidic oxygen evolution electrocatalysts for PEM water electrolyzers',
      journalInfo: 'Journal of the American Chemical Society, 2024, 146, 15515-15524, DOI: 10.1021/jacs.4c04096',
      publicationYear: '2024',
      publicationId: '146, 15515-15524',
      sampleName: 'ZnRuOx; best-performing 3d transition-metal-doped MRuOx candidate',
      synthesis: 'A DFT-guided screening of MRuOx (M = Sc, Ti, V, Cr, Mn, Fe, Co, Ni, Cu, Zn) evaluated Ru dissolution energy; ZnRuOx was synthesized experimentally as the best candidate.',
      activity: 'Acidic OER: ZnRuOx showed robust activity and negligible eta10 decay after 15000 CV cycles.',
      stability: 'PEMWE device stability: 120 h at 200 mA cm-2 using ZnRuOx as anode. Separate acidic OER durability included negligible eta10 decay after 15000 CV cycles.',
      notes: 'Mechanistic point: Zn forms a Zn-rich shell at the nanocrystal exterior, shortens average Ru-O bond lengths, strengthens Ru-O interaction, and improves intrinsic acidic OER stability. The study screened Sc/Ti/V/Cr/Mn/Fe/Co/Ni/Cu/Zn but ZnRuOx was selected for the database entry.',
      pdfFileName: 'sun-et-al-2024-designing-3d-transition-metal-cation-doped-mruox-as-durable-acidic-oxygen-evolution-electrocatalysts-for.pdf',
      pdfFileSize: '5.4 MB',
      pdfUploadedAt: '2026-06-24',
      updatedAt: '2026-06-24',
    },
  ]),
};
