window.PEMWE_AI_ENTRIES = {
  ...(window.PEMWE_AI_ENTRIES || {}),
  B: {
    articles: [
      {
        title: 'Heteroatom dopants overcome the activity-stability trade-off in RuO2 for acidic oxygen evolution',
        journalInfo: 'Nature Communications, 2025, DOI: 10.1038/s41467-025-62036-x',
        publicationYear: '2025',
        publicationId: 'Article 62036-x',
        sampleName: 'Ta/B-RuO2; Ta- and B-codoped nanoporous RuO2 with Ru-O-Ta frameworks and Ru-O-B active sites',
        synthesis: 'Ru-Ta-B precursor ribbons were prepared by melt spinning, then selectively etched by electrochemical corrosion to remove the B-rich phase and transform RuB2 into RuO2. The etched ribbons were annealed in a muffle furnace to obtain a core-shell catalyst containing Ta/B-doped RuO2 shell and Ru-Ta alloy core.',
        activity: 'Acidic OER overpotential of 170 mV at 10 mA cm-2 with a Tafel slope of 44 mV dec-1. In PEMWE, the Ta/B-RuO2 anode reached 1.0 A cm-2 at about 1.6 V and showed polarization up to about 2 A cm-2.',
        stability: 'PEMWE stability: 120 h at 0.2 A cm-2. The reported cell operated around 1.45 V during the 120 h test at 200 mA cm-2, with suppressed Ru dissolution relative to B-RuO2 and RuO2.',
        notes: 'Mechanistic point: Ru-O-Ta frameworks stabilize Ru by mediating bridging oxygen and preferentially replenishing oxygen vacancies, steering OER toward AEM-like behavior. Ru-O-Ta/B sites lower the rate-determining-step barrier. This same article is also listed under Ta because it is a Ta/B codoped RuO2 system.',
        pdfFileName: '7-Ta-RuO2-0.2A-120h-450C.pdf',
        pdfFileSize: '4.2 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  F: {
    articles: [
      {
        title: 'Accelerated Deprotonation Triggered by Fluorinated RuO2 Enables Efficient and Stable Acidic Water Electrolysis',
        journalInfo: 'Journal of the American Chemical Society, 2026, 148, 217-227, DOI: 10.1021/jacs.5c08859',
        publicationYear: '2026',
        publicationId: '148, 217-227',
        sampleName: 'RuO1.86F0.14; fluorinated RuO2',
        synthesis: 'Fluorinated RuO2 was synthesized using nitrate-assisted formation of porous nanomeshes and ammonium fluoride as both fluorinating/etching agent. Nitrate decomposition generated NO2 to promote pores, while HF released from ammonium fluoride introduced F into the RuO2 lattice/surface.',
        activity: 'Acidic OER overpotential of 153 mV at 10 mA cm-2. In PEMWE, RuO1.86F0.14 required only about 1.63 V at 1 A cm-2.',
        stability: 'PEMWE stability: over 100 h at 1 A cm-2. Acidic OER stability exceeded 980 h at 10 mA cm-2 with a degradation rate of about 27 uV h-1.',
        notes: 'Mechanistic point: F- triggers a hydrogen-bond-mediated deprotonation pathway, accelerating proton transfer to bridging oxygen. The high electronegativity of F weakens Ru-O covalency, suppresses Ru overoxidation, and shifts the reaction away from lattice oxygen participation toward AEM-like behavior.',
        pdfFileName: '9-F0.14-RuO1.86-1A-100h-350C-.pdf',
        pdfFileSize: '9.8 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Si: {
    articles: [
      {
        title: 'Bulk and Surface Dual-Modification for Stabilizing RuO2 Anode in 2 A cm-2 PEMWE Operation',
        journalInfo: 'Advanced Materials, 2026, 38, e21819, DOI: 10.1002/adma.202521819',
        publicationYear: '2026',
        publicationId: '38, e21819',
        sampleName: 'Si@CrRuO2; Cr-substituted RuO2 with surface Si modification',
        synthesis: 'Si@CrRuO2 was synthesized by a two-step strategy. Cr was introduced into RuO2 to form CrRuO2 nanoparticles, followed by surface Si modification to create Si-O-Ru interfacial bonding and stabilize the catalyst/electrode interface.',
        activity: 'Cr doping lowered the acidic OER onset/overpotential relative to synthetic RuO2; surface Si modification further improved high-current behavior. PEMWE operation reached 2 A cm-2 at about 1.65 V.',
        stability: 'PEMWE stability: 350 h at 2 A cm-2. The work emphasizes stable industrial-relevant PEMWE operation by combining bulk Ru-valence stabilization with surface/interface protection.',
        notes: 'Mechanistic point: Cr modulates the bulk Ru valence and suppresses overoxidation, while Si stabilizes the reaction interface, inhibits catalyst reconstruction, and helps protect Cr dopants. This same article is also listed under Cr because the functional design is Cr bulk substitution plus Si surface modification.',
        pdfFileName: '5-SiCr-RuO2-2A-350h.pdf',
        pdfFileSize: '6.1 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Cr: {
    articles: [
      {
        title: 'Bulk and Surface Dual-Modification for Stabilizing RuO2 Anode in 2 A cm-2 PEMWE Operation',
        journalInfo: 'Advanced Materials, 2026, 38, e21819, DOI: 10.1002/adma.202521819',
        publicationYear: '2026',
        publicationId: '38, e21819',
        sampleName: 'Si@CrRuO2; Cr-substituted RuO2 with surface Si modification',
        synthesis: 'Si@CrRuO2 was synthesized by a two-step strategy. Cr was introduced into RuO2 to form CrRuO2 nanoparticles, followed by surface Si modification to create Si-O-Ru interfacial bonding and stabilize the catalyst/electrode interface.',
        activity: 'Cr doping lowered the acidic OER onset/overpotential relative to synthetic RuO2; surface Si modification further improved high-current behavior. PEMWE operation reached 2 A cm-2 at about 1.65 V.',
        stability: 'PEMWE stability: 350 h at 2 A cm-2. The work emphasizes stable industrial-relevant PEMWE operation by combining bulk Ru-valence stabilization with surface/interface protection.',
        notes: 'Mechanistic point: Cr modulates the bulk Ru valence and suppresses overoxidation, while Si stabilizes the reaction interface, inhibits catalyst reconstruction, and helps protect Cr dopants. This same article is also listed under Si because the functional design is Cr bulk substitution plus Si surface modification.',
        pdfFileName: '5-SiCr-RuO2-2A-350h.pdf',
        pdfFileSize: '6.1 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Mn: {
    articles: [
      {
        title: 'Hydroxylation Strategy Enables Ru-Mn Oxide for Stable Proton Exchange Membrane Water Electrolysis under 1 A cm-2',
        journalInfo: 'ACS Nano, 2025, 19, 8773-8785, DOI: 10.1021/acsnano.4c15900',
        publicationYear: '2025',
        publicationId: '19, 8773-8785',
        sampleName: 'H-Mn0.1Ru0.9O2; hydroxylated Mn-doped RuO2',
        synthesis: 'Mn-doped RuO2 was prepared using a hydrothermal route, followed by hydrogen peroxide-assisted hydroxylation. The dried black precipitate was annealed in air at 400 C for 3 h to obtain H-Mn0.1Ru0.9O2.',
        activity: 'Acidic OER overpotential of 169 mV at 10 mA cm-2. PEMWE device with H-Mn0.1Ru0.9O2 anode delivered 1 A cm-2 at about 1.65 V.',
        stability: 'PEMWE stability: about 80 h at 1 A cm-2 according to the file label and article title context; the article reports low voltage degradation over continuous tens of hours. Acidic OER stability exceeded 1000 h in electrolyte.',
        notes: 'Mechanistic point: hydroxylation keeps Ru below +4 and, together with Mn doping, promotes AEM rather than LOM. DEMS and DFT support lower energy barrier for *O to *OOH, stronger resistance to subsurface oxygen loss, and suppressed high-valence soluble Ru formation.',
        pdfFileName: '14-H-Mn0.1Ru0.9O2-1A-80h-400C.pdf',
        pdfFileSize: '7.9 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Sn: {
    articles: [
      {
        title: 'Customized reaction route for ruthenium oxide towards stabilized water oxidation in high-performance PEM electrolyzers',
        journalInfo: 'Nature Communications, 2023, DOI: 10.1038/s41467-023-36380-9',
        publicationYear: '2023',
        publicationId: 'Article 36380-9',
        sampleName: 'SnRuOx solid solution; M/Ru close to 1 in rutile-type MRuOx model catalysts',
        synthesis: 'SnRuOx was prepared as a rutile-type MRuOx oxide solid solution using a precursor route based on RuCl3/HMTA chemistry followed by air annealing. The methods section describes annealing dried Ru-HMTA precursor at 350 C for 5 h and acid washing; related MRuOx models were synthesized with controlled metal/Ru ratios.',
        activity: 'The MRuOx model series links Ru charge and OER route. SnRuOx showed favorable acidic OER performance and a customized reaction route relative to RuOx/CeRuOx/CrRuOx, with PEMWE single-cell performance suitable for long-term operation at 1 A cm-2.',
        stability: 'PEMWE stability: 1300 h at 1 A cm-2 with a degradation rate of 53 uV h-1 in a scalable single cell. The two local PDF filenames also indicate 1000-1200 h class durability at 1 A cm-2.',
        notes: 'Mechanistic point: Sn tunes Ru charge and the Ru-O-M motif, customizing the OER route and intermediate binding strength. The central claim is that reaction route, not bias alone, controls operational stability. Two local PDFs appear to be duplicate copies of this same article and are merged into one Sn entry.',
        pdfFileName: '2-SnRuOx-1A-1200h-400C.pdf; 4-SnRuOx-1A-1000h-350C.pdf',
        pdfFileSize: '1.7 MB each',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Zr: {
    articles: [
      {
        title: 'Lewis Acid-Mediated Interfacial Water Supply for Sustainable Proton Exchange Membrane Water Electrolysis',
        journalInfo: 'Journal of the American Chemical Society, 2024, 146, 35438-35448, DOI: 10.1021/jacs.4c14529',
        publicationYear: '2024',
        publicationId: '146, 35438-35448',
        sampleName: 'ZrO2-RuO2; Lewis-acid-modified RuO2 heterostructure',
        synthesis: 'Lewis-acid-modified RuO2 catalysts (ZrO2-RuO2, TiO2-RuO2, HfO2-RuO2) were synthesized by a hydrothermal-annealing strategy. ZrO2-RuO2 is the optimized interfacial-water-supply sample highlighted in the PDF.',
        activity: 'ZrO2-RuO2 displayed an overpotential of 170 mV at 10 mA cm-2 for acidic OER. In PEMWE it maintained robust operation at 2 A cm-2.',
        stability: 'PEMWE stability: 100 h at 2 A cm-2. Acidic OER durability reached 1800 h at 10 mA cm-2 with only about 25 mV degradation, corresponding to about 0.014 mV h-1.',
        notes: 'Mechanistic point: hard Lewis acid ZrO2 modifies interfacial hydrogen bonding and shifts the local water network from rigid hydrogen bonding toward free water, improving water supply and proton transfer. This changes the dissolution/deprotonation environment rather than simply tuning Ru electronic structure.',
        pdfFileName: '11-ZrO2-RuO2-2A-100h-400C.pdf',
        pdfFileSize: '9.8 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Mo: {
    articles: [
      {
        title: 'Heterophase RuO2 oxygen evolution catalyst for durable proton exchange membrane water electrolysis',
        journalInfo: 'Science Advances, 2025',
        publicationYear: '2025',
        publicationId: 'PDF file 1-Mo-RuOx; article details extracted from local PDF',
        sampleName: 'AC-MoRuOx; amorphous-crystalline heterophase Mo-doped RuOx/RuO2 catalyst',
        synthesis: 'Ru acetylacetonate, Mo acetylacetonate, and poly(vinyl pyrrolidone) were dissolved in ethanol, evaporated to a gelatinous precursor, and annealed in air. PVP served as steric stabilizer, pore-forming template, and crystallization regulator to form amorphous-crystalline MoRuOx heterophase architecture.',
        activity: 'Acidic OER overpotential of 180 mV at 10 mA cm-2 with Tafel slope around 48.3 mV dec-1. PEMWE device reached about 2.0 A cm-2 at 1.65 V.',
        stability: 'PEMWE stability: 2000 h at 1.0 A cm-2 and 1000 h at 1.5 A cm-2. Acidic OER stability exceeded 3000 h at 10 mA cm-2 with negligible Ru dissolution.',
        notes: 'Mechanistic point: Mo dopants are enriched near heterophase interfaces, lowering Ru charge and weakening Ru-O covalency. Crystalline domains support electron transport, amorphous domains buffer structural stress, and the heterophase interface addresses the activity-stability trade-off.',
        pdfFileName: '1-Mo-RuOx@1.5A-1000h-400 C.pdf',
        pdfFileSize: '2.5 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  W: {
    articles: [
      {
        title: 'Introducing Bronsted acid sites to accelerate the bridging-oxygen-assisted deprotonation in acidic water oxidation',
        journalInfo: 'Nature Communications, 2022, DOI: 10.1038/s41467-022-32581-w',
        publicationYear: '2022',
        publicationId: 'Article 32581-w',
        sampleName: 'Ru-W binary oxide; rutile RuWOx/RuW5O1x-type catalyst with W-O-Ru Bronsted acid sites',
        synthesis: 'Ru-W binary oxide catalysts were synthesized by a modified sol-gel method. Feed ratios of metal precursors were adjusted to obtain rutile Ru-W oxide nanoparticles with homogeneous Ru, W, and O distribution, followed by drying and annealing at 500 C for 1 h.',
        activity: 'Acidic OER overpotential of 235 mV at 10 mA cm-2. The paper focuses on accelerating proton transfer/deprotonation rather than maximizing PEMWE device current.',
        stability: 'Acidic OER stability: 550 h with low degradation rate of 0.014 mV h-1. The local file name indicates PEMWE-relevant testing around 150 h at 2 A cm-2, but the extracted main-text evidence most clearly supports the 550 h acidic OER durability.',
        notes: 'Mechanistic point: W-O-Ru Bronsted acid sites accelerate bridging-oxygen-assisted deprotonation by facilitating proton transfer from oxo intermediates to neighboring bridging oxygen. The article also states the strategy is extendable to other Ru-M oxides such as Cr, Mo, Nb, Ta, and Ti.',
        pdfFileName: '3-Ru-W oxide-2A-150h-400C.pdf',
        pdfFileSize: '4.0 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Sb: {
    articles: [
      {
        title: 'Accelerated Proton Transfer in Asymmetric Active Units for Sustainable Acidic Oxygen Evolution Reaction',
        journalInfo: 'Journal of the American Chemical Society, 2024, 146, 23146-23157, DOI: 10.1021/jacs.4c05070',
        publicationYear: '2024',
        publicationId: '146, 23146-23157',
        sampleName: 'Ru0.8Sb0.2O2; Sb-containing Ru-M-O binary solid-solution oxide',
        synthesis: 'Ru0.8Sb0.2O2 was synthesized by continuous hydrothermal and calcination strategies to form a rutile solid solution. EDS/ICP-MS showed uniform Ru and Sb mixing; In and Sn analogues were prepared as references.',
        activity: 'Acidic OER overpotential of 160 mV at 10 mA cm-2. The scale-prepared Ru0.8Sb0.2O2 also showed efficient PEMWE performance under industrial conditions.',
        stability: 'PEMWE stability: local file label indicates 500 h at 1 A cm-2. Acidic OER stability was 1100 h at 10 mA cm-2 with low overpotential and ultralow degradation rate.',
        notes: 'Mechanistic point: asymmetric Ru-O-Sb units introduce strong electron delocalization and two-electron Sb redox couples, enabling additional chemical steps during OER and continuous proton transfer. This breaks the scaling-relation limitation while suppressing LOM-associated instability.',
        pdfFileName: '12-Ru0.8Sb0.2O2 -1A-500h-280C.pdf',
        pdfFileSize: '11 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Ta: {
    articles: [
      {
        title: 'Heteroatom dopants overcome the activity-stability trade-off in RuO2 for acidic oxygen evolution',
        journalInfo: 'Nature Communications, 2025, DOI: 10.1038/s41467-025-62036-x',
        publicationYear: '2025',
        publicationId: 'Article 62036-x',
        sampleName: 'Ta/B-RuO2; Ta- and B-codoped nanoporous RuO2 with Ru-O-Ta frameworks and Ru-O-B active sites',
        synthesis: 'Ru-Ta-B precursor ribbons were prepared by melt spinning, then selectively etched by electrochemical corrosion to remove the B-rich phase and transform RuB2 into RuO2. The etched ribbons were annealed in a muffle furnace to obtain a core-shell catalyst containing Ta/B-doped RuO2 shell and Ru-Ta alloy core.',
        activity: 'Acidic OER overpotential of 170 mV at 10 mA cm-2 with a Tafel slope of 44 mV dec-1. In PEMWE, the Ta/B-RuO2 anode reached 1.0 A cm-2 at about 1.6 V and showed polarization up to about 2 A cm-2.',
        stability: 'PEMWE stability: 120 h at 0.2 A cm-2. The reported cell operated around 1.45 V during the 120 h test at 200 mA cm-2, with suppressed Ru dissolution relative to B-RuO2 and RuO2.',
        notes: 'Mechanistic point: Ru-O-Ta frameworks stabilize Ru by mediating bridging oxygen and preferentially replenishing oxygen vacancies, steering OER toward AEM-like behavior. Ru-O-Ta/B sites lower the rate-determining-step barrier. This same article is also listed under B because it is a Ta/B codoped RuO2 system.',
        pdfFileName: '7-Ta-RuO2-0.2A-120h-450C.pdf',
        pdfFileSize: '4.2 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Er: {
    articles: [
      {
        title: 'Lanthanide-regulating Ru-O covalency optimizes acidic oxygen evolution electrocatalysis',
        journalInfo: 'Nature Communications, 2024, DOI: 10.1038/s41467-024-49281-2',
        publicationYear: '2024',
        publicationId: 'Article 49281-2',
        sampleName: 'Er-RuOx; lanthanide-regulated RuOx catalyst',
        synthesis: 'Er-RuOx was prepared by a one-pot glucose-blowing method. Metal precursors, urea, and glucose were heated to form porous foam and annealed at 500 C for 10 h in air to obtain Ln-RuOx; RuO2 was synthesized similarly without lanthanide nitrate.',
        activity: 'Er-RuOx PEMWE device required 1.837 V to reach 3 A cm-2, with reported voltages around 1.590, 1.713, and 1.837 V at 1, 2, and 3 A cm-2. Acidic OER showed improved activity relative to RuO2.',
        stability: 'PEMWE stability: 100 h at 0.5 A cm-2 with degradation rate about 37 uV h-1; the local file name also indicates 100 h class testing at 1 A cm-2. Stability was about 35.5 times higher than RuO2 in the reported comparison.',
        notes: 'Mechanistic point: lanthanide 4f shielding enables continuous tuning of Ru-O covalency. Er gives an optimal volcano-positioned covalency, suppressing lattice oxygen participation and Ru overoxidation while maintaining activity.',
        pdfFileName: '6-Er-RuOx-1A-100h-400C .pdf',
        pdfFileSize: '2.0 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Ir: {
    articles: [
      {
        title: 'Low-iridium stabilized ruthenium oxide anode catalyst for durable proton-exchange membrane water electrolysis',
        journalInfo: 'Nature Nanotechnology, 2025, DOI: 10.1038/s41565-025-02030-y',
        publicationYear: '2025',
        publicationId: 'Article s41565-025-02030-y',
        sampleName: 'Ru6IrOx; Ir-doped RuO2 with Ir:Ru = 1:6 and 14 at.% Ir',
        synthesis: 'RuCl3 and IrCl3.xH2O were dissolved in 3 M HCl, mixed with carbon black for precursor adsorption, dried, annealed in 5% H2/Ar at 800 C for 2 h to form IrRu alloy nanoparticles on carbon, air-annealed at 500 C for 4 h to oxidize and remove carbon, then acid-leached overnight in 1 M HCl, washed and dried. The two-step alloying-to-oxide route was designed to disperse Ir homogeneously inside the RuO2 lattice.',
        activity: 'RDE acidic OER activity was comparable to RuO2, with approximately 240 mV overpotential at 10 mA cm-2 and Tafel slopes around 45-52 mV dec-1. In laboratory PEMWE, Ir-RuOx catalysts showed polarization behaviour similar to RuO2. In a De Nora 25 cm2 PEM electrolyser at 60 C, Ru6IrOx showed nearly identical activity to commercial Ir black up to 1 A cm-2, with slightly higher voltage above 1 A cm-2 despite using roughly one-third of the Ir.',
        stability: 'PEMWE stability: over 1500 h at 2 A cm-2 in laboratory PEMWE with degradation rate of 2.3-2.8 uV h-1. In the 25 cm2 De Nora PEM electrolyser, current was raised to 50 A and held for 1600 h; voltage increased from 1.939 V to 2.000 V in the first 500 h and then decreased to 1.986 V at 1600 h.',
        notes: 'Mechanistic point: DFT and MMC indicate that subsurface Ir, especially first-subsurface Ir, stabilizes neighbouring coordinatively unsaturated Ru sites by increasing Ru vacancy formation energy. XAS supports homogeneous Ir incorporation rather than Ir clustering. Operando Ir L3-edge and Ru K-edge XAS show minimal electronic-structure change during operation.',
        pdfFileName: 's41565-025-02030-y.pdf',
        pdfFileSize: '3.5 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
      {
        title: 'Ultrafast Synthesis of Ir/RuO2 with Enriched Oxygen Vacancies for Durable Acidic Water Electrolysis',
        journalInfo: 'SSRN preprint, 2026, abstract 6055597',
        publicationYear: '2026',
        publicationId: 'SSRN abstract 6055597',
        sampleName: 'Ir/RuO2 via HTS; 1.02 nm Ir clusters anchored on oxygen-vacancy-rich RuO2 nanoparticles',
        synthesis: 'Oxygen-vacancy-rich RuO2 nanoparticles were produced by ultrafast high-temperature shock in about 20 s, followed by wet-chemistry deposition of Ir clusters. The process formed a heterostructured Ir/RuO2 catalyst with stable Ru-O-Ir interfaces.',
        activity: 'Acidic OER overpotential of 150 mV at 10 mA cm-2. PEMWE delivered 1 A cm-2 at about 1.60 V at 60 C.',
        stability: 'PEMWE stability: 100 h at 1 A cm-2. Acidic OER electrolyte stability exceeded 500 h in 0.5 M H2SO4.',
        notes: 'Mechanistic point: oxygen vacancies and interfacial Ru-O-Ir charge transfer promote an AEM-like pathway and suppress Ru overoxidation. Because the PDF is marked as a preprint and not peer reviewed, this entry should be treated as lower-confidence than the journal-published Ir article.',
        pdfFileName: '15.Ir:RuO2 350C 120h 1A.pdf',
        pdfFileSize: '4.7 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Re: {
    articles: [
      {
        title: 'Dynamic rhenium dopant boosts ruthenium oxide for durable oxygen evolution',
        journalInfo: 'Nature Communications, 2023, DOI: 10.1038/s41467-023-35913-6',
        publicationYear: '2023',
        publicationId: 'Article 35913-6',
        sampleName: 'Re0.06Ru0.94O2; dynamic Re-doped RuO2',
        synthesis: 'Re0.06Ru0.94O2 was synthesized by a molten-salt method. NaNO3 and NaReO4 were mixed in a porcelain crucible and heated to 360 C for 10 min; RuCl3.xH2O was then added and held for 5 min. The product was cooled, washed with deionized water to remove salts, and collected by vacuum filtration. Re loading was tuned by changing the amount of NaReO4.',
        activity: 'Acidic OER in O2-saturated 0.1 M HClO4 showed improved activity relative to RuO2, with a Tafel slope of about 45.5 mV dec-1 and high mass activity of 500 A gcat-1 or 7811 A gRe-Ru-1. The paper is primarily an acidic OER mechanistic study rather than a PEMWE single-cell demonstration.',
        stability: 'Acidic OER stability: 200 h at 10 mA cm-2 on carbon paper with 0.2 mgcat cm-2 loading. The potential of Re0.06Ru0.94O2 remained steady, whereas RuO2 decayed within about 19 h. No PEMWE device durability was identified in the main extracted text.',
        notes: 'Mechanistic point: Re acts as a dynamic dopant rather than a static electron-withdrawing substituent. Operando XAS indicates Re accepts electrons at the on-site potential to activate Ru sites, then donates electrons back at high overpotential to suppress Ru dissolution. DEMS, XAS, and DFT support a shift toward AEM, lower oxygen-intermediate adsorption energies, and reduced LOM-driven Ru overoxidation.',
        pdfFileName: 'Re-doped RuOx-200h-360C.pdf',
        pdfFileSize: '2.9 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
  Pb: {
    articles: [
      {
        title: 'Pinning effect of lattice Pb suppressing lattice oxygen reactivity of Pb-RuO2 enables stable industrial-level electrolysis',
        journalInfo: 'Nature Communications, 2024, DOI: 10.1038/s41467-024-53905-y',
        publicationYear: '2024',
        publicationId: 'Article 53905-y',
        sampleName: 'Pb-RuO2; lattice Pb incorporated into RuO2',
        synthesis: 'Pb-RuO2 was prepared by a one-pot glucose-blowing method. A porous foam containing homogeneously dispersed Ru and Pb ions was first obtained, then calcined in air to form Pb-RuO2. Pure RuO2 was synthesized by the same process without Pb.',
        activity: 'Acidic OER showed low overpotential and improved kinetics relative to home-made and commercial RuO2; the extracted figure text indicates approximately 21 mV decay over 1000 h in acidic OER. PEMWE performance was evaluated at industrial-level current.',
        stability: 'PEMWE stability: 100 h at 1 A cm-2 with low degradation rate of about 17 uV h-1 according to the abstract/file label. Acidic OER stability also showed very small decay over 1000 h.',
        notes: 'Mechanistic point: large, acid-resistant lattice Pb pins oxygen-atom migration channels, reduces lattice oxygen reactivity, lowers Ru-O covalency through 6s-2p-4d orbital hybridization, and suppresses Ru overoxidation. The article frames this as a lattice-oxygen-reactivity control strategy for PEMWE durability.',
        pdfFileName: '13-Pb-RuO2-1A-100h-500C.pdf',
        pdfFileSize: '2.8 MB',
        pdfUploadedAt: '2026-06-23',
        updatedAt: '2026-06-23',
      },
    ],
  },
};
